-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.clientes (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  sp_id integer NOT NULL UNIQUE,
  sp_modified timestamp with time zone,
  created_sp timestamp with time zone,
  modified_by text,
  tp_prazos_pg text,
  cod_cliente text,
  conta_transf text,
  nombre_comercial text,
  razon_social text,
  cif_dni text,
  cif_europeo text,
  domicilio text,
  codigo_postal text,
  municipio text,
  provincia text,
  pais text,
  telefono text,
  movil text,
  email text,
  email_envio_factura text,
  iban text,
  latitude text,
  longitude text,
  comentarios text,
  id_pais integer,
  nombre_resp_empresa text,
  nombre_resp_documentacion text,
  nombre_resp_facturacion text,
  telefono_resp_empresa text,
  telefono_resp_documentacion text,
  telefono_facturacion text,
  email_cobros text,
  resp_cobros text,
  telefono_cobros text,
  funcions_clientes jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT clientes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.colaboradores (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  sp_id integer NOT NULL UNIQUE,
  sp_modified timestamp with time zone,
  cod_colab text,
  nombre text,
  pasaporte text,
  fecha_nacimiento text,
  nacionalidade text,
  dni text,
  nie text,
  movil text,
  niss text,
  nif text,
  status_seguridad text,
  fecha_alta text,
  fecha_baja text,
  ubicacion text,
  fecha_inicio text,
  fecha_fin_pedido text,
  fecha_salida_trabajador text,
  camiseta text,
  pantalones text,
  transporte text,
  licencia_conducir text,
  alojamiento text,
  status_trabajador text,
  motivo_salida text,
  comentarios text,
  funcion text,
  contratante text,
  email text,
  foto text,
  domicilio text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT colaboradores_pkey PRIMARY KEY (id)
);
CREATE TABLE public.colaboradores_reemplazados (
  id bigint NOT NULL DEFAULT nextval('colaboradores_reemplazados_id_seq'::regclass),
  sp_id bigint NOT NULL UNIQUE,
  sp_created timestamp with time zone,
  sp_modified timestamp with time zone,
  sp_created_by text,
  sp_modified_by text,
  cod_reemplazo text,
  cod_pedido text,
  cod_cliente text,
  nombre_colaborador text,
  cod_colaborador text,
  funcion text,
  cantidad text,
  fecha_inicio_reemplazo timestamp with time zone,
  fecha_fin_reemplazo timestamp with time zone,
  observaciones text,
  CONSTRAINT colaboradores_reemplazados_pkey PRIMARY KEY (id)
);
CREATE TABLE public.colaboradores_reubicados (
  id bigint NOT NULL DEFAULT nextval('colaboradores_reubicados_id_seq'::regclass),
  sp_id bigint UNIQUE,
  sp_created timestamp with time zone,
  sp_modified timestamp with time zone,
  sp_created_by text,
  sp_modified_by text,
  cod_reubicacion text,
  cod_pedido text,
  cod_cliente text,
  nombre_colaborador text,
  cod_colab text,
  funcion text,
  cantidad text,
  fecha_inicio_reubicacion timestamp with time zone,
  fecha_fin_reubicacion timestamp with time zone,
  observaciones text,
  CONSTRAINT colaboradores_reubicados_pkey PRIMARY KEY (id)
);
CREATE TABLE public.contas_receber (
  id bigint NOT NULL DEFAULT nextval('contas_receber_id_seq'::regclass),
  sp_id integer NOT NULL,
  sp_modified timestamp with time zone,
  empresa text,
  cod_cliente text,
  cliente text,
  obra text,
  periodo_fat text,
  data_emissao text,
  competencia text,
  dt_venc text,
  moeda text,
  valot_total text,
  status text,
  origem text,
  cat_receita text,
  centro_custo text,
  conta_contab text,
  num_doc text,
  obs text,
  creado text,
  creado_por text,
  banco text,
  comentarios text,
  form_receb text,
  comisao_taxa text,
  hist_valor_parcial text,
  integral_parcial text,
  prev_pag text,
  saldo_a_pagar text,
  tipo_cobros text,
  valor_parcial text,
  obs_recebimento text,
  dt_recebimento text,
  modificado text,
  modificado_por text,
  CONSTRAINT contas_receber_pkey PRIMARY KEY (id)
);
CREATE TABLE public.contratados (
  id bigint NOT NULL DEFAULT nextval('contratados_id_seq'::regclass),
  sp_id bigint UNIQUE,
  sp_created timestamp with time zone,
  sp_modified timestamp with time zone,
  sp_created_by text,
  sp_modified_by text,
  cod_colab text,
  nombre text,
  movil text,
  tarifa_acordada_trab text,
  id_funcion text,
  cod_servico text,
  tipo_servico text,
  camisa text,
  pantalone text,
  licencia_de_conducir text,
  observaciones text,
  fecha_nascto timestamp with time zone,
  pasaporte text,
  CONSTRAINT contratados_pkey PRIMARY KEY (id)
);
CREATE TABLE public.empresas (
  id bigint NOT NULL DEFAULT nextval('empresas_id_seq'::regclass),
  sp_id bigint NOT NULL UNIQUE,
  sp_created timestamp with time zone,
  sp_modified timestamp with time zone,
  sp_created_by text,
  sp_modified_by text,
  nome_pbi text,
  razon_social text,
  nombre_comercial text,
  cif_dni text,
  cif_europeo text,
  conta_transf text,
  domicilio text,
  codigo_postal text,
  municipio text,
  provincia text,
  pais text,
  telefono text,
  movil text,
  email text,
  email_envio_factura text,
  email_cobros text,
  iban text,
  latitude text,
  longitude text,
  comentarios text,
  nombre_resp_empresa text,
  nombre_resp_documentacion text,
  nombre_resp_facturacion text,
  telefono_resp_empresa text,
  telefono_resp_documentacion text,
  telefono_facturacion text,
  resp_cobros text,
  telefono_cobros text,
  CONSTRAINT empresas_pkey PRIMARY KEY (id)
);
CREATE TABLE public.estimaciones (
  id bigint NOT NULL DEFAULT nextval('estimaciones_id_seq'::regclass),
  sp_id bigint NOT NULL UNIQUE,
  sp_modified timestamp with time zone,
  title text,
  comercial_ventas text,
  correo_comercial text,
  nombre text,
  id_cliente text,
  empresa text,
  externo text,
  empresa_interna text,
  id_firma_digital text,
  correo_adm_ventas text,
  correo_central_ventas text,
  correo_coordinacion_ei text,
  correo_prl_ei text,
  fecha_inicio timestamp with time zone,
  fecha_final timestamp with time zone,
  direccion text,
  codigo_postal text,
  pruebas text,
  inicio_prueba timestamp with time zone,
  fin_prueba timestamp with time zone,
  direccion_pruebas text,
  codigo_postal_pruebas text,
  lunes boolean,
  martes boolean,
  miercoles boolean,
  jueves boolean,
  viernes boolean,
  sabado boolean,
  domingo boolean,
  completa_estandar text,
  inserted_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT estimaciones_pkey PRIMARY KEY (id)
);
CREATE TABLE public.funcion (
  id bigint NOT NULL DEFAULT nextval('funcion_id_seq'::regclass),
  sp_id bigint UNIQUE,
  sp_created timestamp with time zone,
  sp_modified timestamp with time zone,
  sp_created_by text,
  sp_modified_by text,
  cod_funcion text,
  nombre text,
  descripcion text,
  status_funcion text,
  analise_risco text,
  perguntas text,
  grupo_funcion text,
  tarifa_cliente text,
  dias_habiles text,
  nomina_completa text,
  coste_epi text,
  CONSTRAINT funcion_pkey PRIMARY KEY (id)
);
CREATE TABLE public.itens_pedido (
  id bigint NOT NULL DEFAULT nextval('itens_pedido_id_seq'::regclass),
  sp_id bigint NOT NULL,
  sp_created timestamp with time zone,
  sp_modified timestamp with time zone,
  sp_created_by text,
  sp_modified_by text,
  cod_pedido text,
  nombre_perfil text,
  cantidad numeric,
  descripcion_trabajo text,
  id_funcion_col bigint,
  analise_risco text,
  CONSTRAINT itens_pedido_pkey PRIMARY KEY (id)
);
CREATE TABLE public.itens_reemplazo (
  id bigint NOT NULL DEFAULT nextval('itens_reemplazo_id_seq'::regclass),
  sp_id bigint NOT NULL UNIQUE,
  sp_modified timestamp with time zone,
  creado_sp timestamp with time zone,
  creado_por text,
  modificado_por text,
  cod_reemplazo text,
  cod_pedido text,
  cantidad bigint,
  descripcion_trabajo text,
  nombre_perfil text,
  id_funcion_col bigint,
  analise_risco text,
  sp_created timestamp with time zone,
  sp_created_by text,
  sp_modified_by text,
  CONSTRAINT itens_reemplazo_pkey PRIMARY KEY (id)
);
CREATE TABLE public.mcs_department_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  department_id uuid NOT NULL,
  user_id uuid,
  member_role text NOT NULL DEFAULT 'member'::text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  nombrecompleto text,
  correoempresarial text,
  ubicaciontrabajo text,
  codigoresponsabilidad text,
  telefonodirecto text,
  extenciontelefonica text,
  fechainicio date,
  fechanacimiento date,
  estadotrabajador text,
  iban text,
  empresa_contratante_id bigint,
  empresa_servicos_id bigint,
  usuario text,
  CONSTRAINT mcs_department_members_pkey PRIMARY KEY (id),
  CONSTRAINT mcs_department_members_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.mcs_departments(id),
  CONSTRAINT mcs_department_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.mcs_users(id),
  CONSTRAINT mcs_department_members_empresa_contratante_id_fkey FOREIGN KEY (empresa_contratante_id) REFERENCES public.empresas(id),
  CONSTRAINT mcs_department_members_empresa_servicos_id_fkey FOREIGN KEY (empresa_servicos_id) REFERENCES public.empresas(id)
);
CREATE TABLE public.mcs_departments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT mcs_departments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.mcs_entity_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entity_type text NOT NULL,
  entity_id uuid NOT NULL,
  source_system text NOT NULL,
  source_table text NOT NULL,
  source_sp_id integer,
  source_id uuid,
  source_ref text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT mcs_entity_links_pkey PRIMARY KEY (id)
);
CREATE TABLE public.mcs_incident_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  incident_id uuid NOT NULL,
  step_order integer NOT NULL,
  title text NOT NULL,
  department_id uuid,
  sla_days integer NOT NULL DEFAULT 1,
  due_at timestamp with time zone,
  status text NOT NULL DEFAULT 'open'::text,
  assigned_to_email text,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  last_status_change_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT mcs_incident_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT mcs_incident_tasks_incident_id_fkey FOREIGN KEY (incident_id) REFERENCES public.mcs_incidents(id),
  CONSTRAINT mcs_incident_tasks_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.mcs_departments(id)
);
CREATE TABLE public.mcs_incidents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  incident_type text NOT NULL,
  status text NOT NULL DEFAULT 'open'::text,
  playbook_id uuid,
  origin_system text,
  origin_table text,
  origin_sp_id integer,
  origin_ref text,
  client_sp_id integer,
  pedido_sp_id integer,
  worker_sp_id integer,
  obra_sp_id integer,
  company_sp_id integer,
  title text NOT NULL,
  description text,
  context_json jsonb,
  created_by_email text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  origin_code text,
  empresa_id integer,
  cliente_id integer,
  pedido_code text,
  CONSTRAINT mcs_incidents_pkey PRIMARY KEY (id),
  CONSTRAINT mcs_incidents_playbook_id_fkey FOREIGN KEY (playbook_id) REFERENCES public.mcs_playbooks(id)
);
CREATE TABLE public.mcs_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_email text NOT NULL,
  type text NOT NULL,
  severity text NOT NULL DEFAULT 'info'::text,
  title text NOT NULL,
  message text,
  entity_type text,
  entity_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  read_at timestamp with time zone,
  CONSTRAINT mcs_notifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.mcs_playbook_steps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  playbook_id uuid NOT NULL,
  step_order integer NOT NULL,
  task_template_id uuid NOT NULL,
  override_title_pt text,
  override_title_es text,
  override_department_id uuid,
  override_sla_days integer,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT mcs_playbook_steps_pkey PRIMARY KEY (id),
  CONSTRAINT mcs_playbook_steps_playbook_id_fkey FOREIGN KEY (playbook_id) REFERENCES public.mcs_playbooks(id),
  CONSTRAINT mcs_playbook_steps_task_template_id_fkey FOREIGN KEY (task_template_id) REFERENCES public.mcs_task_templates(id),
  CONSTRAINT mcs_playbook_steps_override_department_id_fkey FOREIGN KEY (override_department_id) REFERENCES public.mcs_departments(id)
);
CREATE TABLE public.mcs_playbooks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name_pt text NOT NULL,
  name_es text,
  incident_type text NOT NULL,
  description_pt text,
  description_es text,
  version integer NOT NULL DEFAULT 1,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT mcs_playbooks_pkey PRIMARY KEY (id)
);
CREATE TABLE public.mcs_task_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title_pt text NOT NULL,
  title_es text,
  description_pt text,
  description_es text,
  default_department_id uuid,
  default_sla_days integer NOT NULL DEFAULT 1,
  priority text NOT NULL DEFAULT 'normal'::text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT mcs_task_templates_pkey PRIMARY KEY (id),
  CONSTRAINT mcs_task_templates_default_department_id_fkey FOREIGN KEY (default_department_id) REFERENCES public.mcs_departments(id)
);
CREATE TABLE public.mcs_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  display_name text,
  role text NOT NULL DEFAULT 'user'::text,
  language text NOT NULL DEFAULT 'pt'::text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  department_id uuid,
  CONSTRAINT mcs_users_pkey PRIMARY KEY (id),
  CONSTRAINT mcs_users_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.mcs_departments(id)
);
CREATE TABLE public.pedidos (
  id bigint NOT NULL DEFAULT nextval('pedidos_id_seq'::regclass),
  sp_id integer NOT NULL,
  sp_modified timestamp with time zone,
  created_sp timestamp with time zone,
  modified_sp timestamp with time zone,
  created_by text,
  modified_by text,
  cod_pedido text,
  ubicacion_trabajo text,
  fecha_inicio_pedido timestamp with time zone,
  fecha_fin_pedido timestamp with time zone,
  fecha_emision timestamp with time zone,
  horas_trabalho_dia text,
  responsavel_obra text,
  movil_responsavel text,
  hora_inicio_trabalho text,
  comercial_responsable text,
  solicitado_por text,
  tarifa_contratada text,
  tipo_trabajo text,
  observacoes text,
  status_pedido text,
  id_cliente integer,
  cod_cliente text,
  id_empresa integer,
  id_pais integer,
  id_region integer,
  pergunta_respuesta text,
  CONSTRAINT pedidos_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  full_name text,
  role text DEFAULT 'user'::text CHECK (role = ANY (ARRAY['admin'::text, 'user'::text, 'manager'::text])),
  department text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.reemplazos (
  id bigint NOT NULL DEFAULT nextval('reemplazos_id_seq'::regclass),
  sp_id bigint NOT NULL UNIQUE,
  created_sp timestamp with time zone,
  sp_modified timestamp with time zone,
  sp_created_by text,
  sp_modified_by text,
  tarifacontratada text,
  codreemplazo text,
  codpedido text,
  codcliente text,
  idcliente integer,
  idempresa text,
  comercialresponsable text,
  fechaemision text,
  solicitadopor text,
  umbicaciontrabajo text,
  idpais text,
  idregion text,
  fechainicioreemplazo text,
  fechafinreemplazo text,
  fechafincolab text,
  horastrabalhodia text,
  horainiciotrabalho text,
  responsavelobra text,
  movilresponsavel text,
  observacoes text,
  preguntarespuesta text,
  statusreemplazo text,
  tipotrabajo text,
  inserted_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT reemplazos_pkey PRIMARY KEY (id)
);
CREATE TABLE public.reubicaciones (
  id bigint NOT NULL DEFAULT nextval('reubicaciones_id_seq'::regclass),
  sp_id bigint UNIQUE,
  sp_created timestamp with time zone,
  sp_modified timestamp with time zone,
  sp_created_by text,
  sp_modified_by text,
  cod_reubicaciones text,
  cliente text,
  empresa text,
  status_reubicaciones text,
  observacoes text,
  id_empresa text,
  id_cliente text,
  fecha_emision timestamp with time zone,
  fecha_inicio_reubicacion timestamp with time zone,
  fecha_fin_reubicacion timestamp with time zone,
  cod_pedido text,
  comercial_responsable text,
  solicitado_por text,
  id_pais text,
  id_regiao text,
  id_region text,
  umbicacion_trabajo text,
  horas_trabajo_dia text,
  hora_inicio_dia text,
  movil_responsable text,
  responsable_obra text,
  tipo_trabajo text,
  cod_cliente text,
  CONSTRAINT reubicaciones_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sync_state (
  entity text NOT NULL,
  last_modified_sp timestamp with time zone,
  last_run_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sync_state_pkey PRIMARY KEY (entity)
);