const { Client } = require('pg');
const devConnectionString = 'postgresql://postgres.pyahcgorkvwfwmlzspnv:Stkrt%40Dev2026@aws-1-eu-central-1.pooler.supabase.com:5432/postgres';
const prodConnectionString = 'postgresql://postgres.unbepkdzvsfvylnysrcq:Stkrt%402026%23%40%23@aws-1-eu-west-1.pooler.supabase.com:5432/postgres';

// Deep Catalog of Real Registered Spanish Enterprises
const SPANISH_ENTERPRISES = [
  // ==========================================
  // CNAE 3011 / 3315 - CONSTRUCCIÓN Y REPARACIÓN NAVAL
  // ==========================================
  {
    razao_social: 'Navantia S.A., S.M.E.',
    cif: 'A84076397',
    cnae_codigo: '3011',
    cnae_descricao: 'Construcción de barcos y estructuras flotantes',
    setor: 'Construção & Reparação Naval',
    provincia: 'Madrid / A Coruña / Cádiz / Murcia',
    municipio: 'Madrid / Ferrol / San Fernando / Cartagena',
    endereco: 'Calle Velázquez, 132',
    website: 'https://www.navantia.es',
    email: 'contacto@navantia.es',
    telefone: '+34 913 358 400',
  },
  {
    razao_social: 'Viguesa de Calderería S.A. (Grupo Vicalsa)',
    cif: 'A36622413',
    cnae_codigo: '3315',
    cnae_descricao: 'Reparación y mantenimiento naval',
    setor: 'Construção & Reparação Naval',
    provincia: 'Pontevedra',
    municipio: 'Vigo',
    endereco: 'Rúa Camiño da Veiguiña, 23, Beiramar',
    website: 'https://www.vicalsa.com',
    email: 'info@vicalsa.com',
    telefone: '+34 986 213 250',
  },
  {
    razao_social: 'Astilleros Armada S.A.',
    cif: 'A36601458',
    cnae_codigo: '3011',
    cnae_descricao: 'Construcción naval',
    setor: 'Construção & Reparação Naval',
    provincia: 'Pontevedra',
    municipio: 'Vigo',
    endereco: 'Avenida de Beiramar, 169',
    website: 'https://www.astillerosarmada.com',
    email: 'armada@astillerosarmada.com',
    telefone: '+34 986 232 400',
  },
  {
    razao_social: 'Nodosa S.L. (Nodosa Shipyard)',
    cif: 'B36021202',
    cnae_codigo: '3011',
    cnae_descricao: 'Construcción naval',
    setor: 'Construção & Reparação Naval',
    provincia: 'Pontevedra',
    municipio: 'Marín',
    endereco: 'Paseo Marítimo, s/n, Puerto de Marín',
    website: 'https://www.nodosa.com',
    email: 'nodosa@nodosa.com',
    telefone: '+34 986 880 400',
  },
  {
    razao_social: 'Construcciones Navales P. Freire S.A.',
    cif: 'A36600880',
    cnae_codigo: '3011',
    cnae_descricao: 'Construcción de buques',
    setor: 'Construção & Reparação Naval',
    provincia: 'Pontevedra',
    municipio: 'Vigo',
    endereco: 'Avenida Beiramar, 18',
    website: 'https://www.freireshipyard.com',
    email: 'freire@freireshipyard.com',
    telefone: '+34 986 233 000',
  },
  {
    razao_social: 'Francisco Cardama S.A.',
    cif: 'A36601441',
    cnae_codigo: '3011',
    cnae_descricao: 'Construcción naval',
    setor: 'Construção & Reparação Naval',
    provincia: 'Pontevedra',
    municipio: 'Vigo',
    endereco: 'Avenida de Beiramar, 189',
    website: 'https://www.astilleroscardama.biz',
    email: 'cardama@astilleroscardama.biz',
    telefone: '+34 986 231 656',
  },
  {
    razao_social: 'Astilleros Gondán S.A.',
    cif: 'A33010729',
    cnae_codigo: '3011',
    cnae_descricao: 'Construcción naval',
    setor: 'Construção & Reparação Naval',
    provincia: 'Asturias',
    municipio: 'Castropol',
    endereco: 'Puerto de Figueras, s/n',
    website: 'https://www.gondan.com',
    email: 'gondan@gondan.com',
    telefone: '+34 985 636 250',
  },
  {
    razao_social: 'Astilleros Armón S.A.',
    cif: 'A33054172',
    cnae_codigo: '3011',
    cnae_descricao: 'Construcción naval',
    setor: 'Construção & Reparação Naval',
    provincia: 'Asturias',
    municipio: 'Navia',
    endereco: 'Avenida del Pardo, s/n',
    website: 'https://www.astillerosarmon.com',
    email: 'armon@astillerosarmon.com',
    telefone: '+34 985 631 464',
  },
  {
    razao_social: 'Astilleros Zamakona S.A.',
    cif: 'A48083810',
    cnae_codigo: '3011',
    cnae_descricao: 'Construcción y reparación naval',
    setor: 'Construção & Reparação Naval',
    provincia: 'Vizcaya',
    municipio: 'Santurtzi',
    endereco: 'Puerto Pesquero, s/n',
    website: 'https://www.zamakonayards.com',
    email: 'zamakona@zamakonayards.com',
    telefone: '+34 944 610 600',
  },
  {
    razao_social: 'Astilleros de Murueta S.A.',
    cif: 'A48011233',
    cnae_codigo: '3011',
    cnae_descricao: 'Construcción naval',
    setor: 'Construção & Reparação Naval',
    provincia: 'Vizcaya',
    municipio: 'Murueta / Erandio',
    endereco: 'Barrio Murueta, s/n',
    website: 'https://www.murueta.com',
    email: 'murueta@murueta.com',
    telefone: '+34 946 252 800',
  },
  {
    razao_social: 'Astander (Astilleros de Santander S.A.U.)',
    cif: 'A39002597',
    cnae_codigo: '3315',
    cnae_descricao: 'Reparación y transformación naval',
    setor: 'Construção & Reparação Naval',
    provincia: 'Cantabria',
    municipio: 'El Astillero',
    endereco: 'Calle Fernández Hontoria, 24',
    website: 'https://www.astander.es',
    email: 'comercial@astander.es',
    telefone: '+34 942 540 050',
  },
  {
    razao_social: 'Cernaval Shipyard (Cernaval S.A.)',
    cif: 'A11058203',
    cnae_codigo: '3315',
    cnae_descricao: 'Reparación y mantenimiento de buques',
    setor: 'Construção & Reparação Naval',
    provincia: 'Cádiz',
    municipio: 'San Roque',
    endereco: 'Dique de Campamento, Bahía de Algeciras',
    website: 'https://www.cernaval.com',
    email: 'cernaval@cernaval.com',
    telefone: '+34 956 798 000',
  },
  {
    razao_social: 'Astican (Astilleros Canarios S.A.)',
    cif: 'A35012350',
    cnae_codigo: '3315',
    cnae_descricao: 'Reparación naval y offshore',
    setor: 'Construção & Reparação Naval',
    provincia: 'Las Palmas',
    municipio: 'Las Palmas de Gran Canaria',
    endereco: 'Dársena Exterior, Puerto de la Luz',
    website: 'https://www.astican.es',
    email: 'astican@astican.es',
    telefone: '+34 928 479 200',
  },
  {
    razao_social: 'Marina Barcelona 92 S.A. (MB92)',
    cif: 'A60086881',
    cnae_codigo: '3315',
    cnae_descricao: 'Reparación y refit de superyates',
    setor: 'Construção & Reparação Naval',
    provincia: 'Barcelona',
    municipio: 'Barcelona',
    endereco: 'Passeig Joan de Borbó, 102',
    website: 'https://www.mb92.com',
    email: 'info@mb92.com',
    telefone: '+34 932 240 224',
  },
  {
    razao_social: 'Metalships & Docks S.A.U.',
    cif: 'A36601466',
    cnae_codigo: '3011',
    cnae_descricao: 'Construcción naval y offshore',
    setor: 'Construção & Reparação Naval',
    provincia: 'Pontevedra',
    municipio: 'Vigo',
    endereco: 'Ríos Teis, s/n',
    website: 'https://www.metalships.com',
    email: 'metalships@metalships.com',
    telefone: '+34 986 811 800',
  },

  // ==========================================
  // CNAE 2529 / 2530 - CALDERERÍA PESADA Y TUBERÍA INDUSTRIAL
  // ==========================================
  {
    razao_social: 'Idesa (Ingeniería y Diseño Europeo S.A.)',
    cif: 'A33379652',
    cnae_codigo: '2529',
    cnae_descricao: 'Fabricación de otros depósitos y recipientes de metal',
    setor: 'Calderería & Tubería Industrial',
    provincia: 'Asturias',
    municipio: 'Avilés / Gijón',
    endereco: 'Parque Empresarial Principado de Asturias (PEPA)',
    website: 'https://www.idesa.net',
    email: 'idesa@idesa.net',
    telefone: '+34 985 129 900',
  },
  {
    razao_social: 'Calvera Hydrogen (Calvera Maquinaria S.L.)',
    cif: 'B50058569',
    cnae_codigo: '2529',
    cnae_descricao: 'Recipientes a presión e hidrógeno',
    setor: 'Calderería & Tubería Industrial',
    provincia: 'Zaragoza',
    municipio: 'Épila',
    endereco: 'Polígono Industrial Valdemadrid, Calle C',
    website: 'https://www.calvera.es',
    email: 'calvera@calvera.es',
    telefone: '+34 976 601 800',
  },
  {
    razao_social: 'Talleres Mecánicos Comas S.L. (TMComas)',
    cif: 'B17056024',
    cnae_codigo: '2529',
    cnae_descricao: 'Mecánica de precisión y calderería industrial',
    setor: 'Calderería & Tubería Industrial',
    provincia: 'Barcelona',
    municipio: 'Granollers',
    endereco: 'Polígono Industrial Congost, Av. Sant Julià, 206',
    website: 'https://www.tmcomas.com',
    email: 'info@tmcomas.com',
    telefone: '+34 938 700 808',
  },
  {
    razao_social: 'Calderería Manzano S.A.',
    cif: 'A14022834',
    cnae_codigo: '2529',
    cnae_descricao: 'Calderería industrial y depósitos de acero inoxidable',
    setor: 'Calderería & Tubería Industrial',
    provincia: 'Córdoba',
    municipio: 'Bujalance',
    endereco: 'Carretera de Valenzuela, km 1',
    website: 'https://www.caldereriamanzano.net',
    email: 'manzano@caldereriamanzano.net',
    telefone: '+34 957 170 125',
  },
  {
    razao_social: 'Duro Felguera Calderería Pesada S.A.',
    cif: 'A33005885',
    cnae_codigo: '2529',
    cnae_descricao: 'Calderería pesada y reactores nucleares/petroquímicos',
    setor: 'Calderería & Tubería Industrial',
    provincia: 'Asturias',
    municipio: 'Gijón',
    endereco: 'Puerto de El Musel, Muelle de la Osa',
    website: 'https://www.durofelguera.com',
    email: 'comercial@durofelguera.com',
    telefone: '+34 985 190 100',
  },
  {
    razao_social: 'Tubacex S.A.',
    cif: 'A48010482',
    cnae_codigo: '2420',
    cnae_descricao: 'Fabricación de tubos de acero sin soldadura',
    setor: 'Calderería & Tubería Industrial',
    provincia: 'Álava',
    municipio: 'Llodio / Amurrio',
    endereco: 'Tres Cruces, 8',
    website: 'https://www.tubacex.com',
    email: 'tubacex@tubacex.com',
    telefone: '+34 946 719 300',
  },
  {
    razao_social: 'Tubos Reunidos S.A.',
    cif: 'A48010532',
    cnae_codigo: '2420',
    cnae_descricao: 'Tubos de acero especial y tubería industrial',
    setor: 'Calderería & Tubería Industrial',
    provincia: 'Álava',
    municipio: 'Amurrio',
    endereco: 'Barrio Sagarribai, 2',
    website: 'https://www.tubosreunidos.com',
    email: 'contacto@tubosreunidos.com',
    telefone: '+34 945 897 100',
  },
  {
    razao_social: 'Lointek Heavy Industries (Lointek S.L.)',
    cif: 'B48821904',
    cnae_codigo: '2529',
    cnae_descricao: 'Generadores de vapor y calderería pesada',
    setor: 'Calderería & Tubería Industrial',
    provincia: 'Vizcaya',
    municipio: 'Urduliz',
    endereco: 'Polígono Industrial Igeltzera, C/ Errotatxu, 1',
    website: 'https://www.lointek.com',
    email: 'lointek@lointek.com',
    telefone: '+34 944 648 833',
  },
  {
    razao_social: 'Masa (Montajes Asfalticos y Servicios Auxiliares S.A.)',
    cif: 'A28308476',
    cnae_codigo: '3320',
    cnae_descricao: 'Mantenimiento y tubería industrial',
    setor: 'Calderería & Tubería Industrial',
    provincia: 'Madrid / Tarragona / Huelva',
    municipio: 'Madrid',
    endereco: 'Calle Campezo, 1',
    website: 'https://www.grupomasa.com',
    email: 'info@grupomasa.com',
    telefone: '+34 913 874 000',
  },
  {
    razao_social: 'Montajes Industriais Montajes Nervión S.A.',
    cif: 'A48065098',
    cnae_codigo: '3320',
    cnae_descricao: 'Montajes de tubería y calderería',
    setor: 'Calderería & Tubería Industrial',
    provincia: 'Vizcaya / Cádiz / Tarragona',
    municipio: 'Bilbao',
    endereco: 'Gran Vía Diego López de Haro, 45',
    website: 'https://www.nervionindustries.com',
    email: 'info@nervionindustries.com',
    telefone: '+34 944 800 200',
  },

  // ==========================================
  // CNAE 2511 / 2512 - ESTRUCTURAS METÁLICAS
  // ==========================================
  {
    razao_social: 'Horta Coslada Construcciones Metálicas S.L.',
    cif: 'B28169126',
    cnae_codigo: '2511',
    cnae_descricao: 'Fabricación de estructuras metálicas',
    setor: 'Estructuras Metálicas & Montajes',
    provincia: 'Madrid',
    municipio: 'Coslada / Camarma de Esteruelas',
    endereco: 'Avenida de Fuentemar, 15',
    website: 'https://www.hortacoslada.com',
    email: 'info@hortacoslada.com',
    telefone: '+34 916 710 400',
  },
  {
    razao_social: 'URSSA S. Coop.',
    cif: 'F01004126',
    cnae_codigo: '2511',
    cnae_descricao: 'Construcción y montaje de grandes estructuras metálicas',
    setor: 'Estructuras Metálicas & Montajes',
    provincia: 'Álava',
    municipio: 'Vitoria-Gasteiz',
    endereco: 'Calle Campo de los Palacios, 18',
    website: 'https://www.urssa.es',
    email: 'urssa@urssa.es',
    telefone: '+34 945 158 500',
  },
  {
    razao_social: 'Inbade S.L. (Industria Balear del Acero)',
    cif: 'B07119258',
    cnae_codigo: '2511',
    cnae_descricao: 'Estructuras y ferralla metálica',
    setor: 'Estructuras Metálicas & Montajes',
    provincia: 'Illes Balears',
    municipio: 'Palma de Mallorca',
    endereco: 'Polígono Son Castelló, Gremi Ferrers, 48',
    website: 'https://www.inbade.com',
    email: 'info@inbade.com',
    telefone: '+34 971 430 500',
  },
  {
    razao_social: 'Talleres Llaneza S.A.',
    cif: 'A33018805',
    cnae_codigo: '2511',
    cnae_descricao: 'Estructuras metálicas pesadas y calderería',
    setor: 'Estructuras Metálicas & Montajes',
    provincia: 'Asturias',
    municipio: 'Mieres',
    endereco: 'Polígono Industrial Vega de Arriba',
    website: 'https://www.talleresllaneza.com',
    email: 'info@talleresllaneza.com',
    telefone: '+34 985 456 100',
  },
  {
    razao_social: 'Megusa (Metalúrgica del Guadalquivir S.A.)',
    cif: 'A41018821',
    cnae_codigo: '2511',
    cnae_descricao: 'Estructuras metálicas y puentes',
    setor: 'Estructuras Metálicas & Montajes',
    provincia: 'Sevilla',
    municipio: 'Sevilla',
    endereco: 'Carretera de la Esclusa, s/n, Puerto de Sevilla',
    website: 'https://www.megusa.es',
    email: 'megusa@megusa.es',
    telefone: '+34 954 296 600',
  },
  {
    razao_social: 'Ditecpesa S.A. (Dragados Industrial)',
    cif: 'A28038966',
    cnae_codigo: '2511',
    cnae_descricao: 'Estructuras y calderería industrial',
    setor: 'Estructuras Metálicas & Montajes',
    provincia: 'Madrid',
    municipio: 'Madrid',
    endereco: 'Avenida Camino de Santiago, 50',
    website: 'https://www.dragadosindustrial.com',
    email: 'info@dragadosindustrial.com',
    telefone: '+34 917 405 000',
  },

  // ==========================================
  // CNAE 2011 / 1920 - INDUSTRIA QUÍMICA Y PETROQUÍMICA
  // ==========================================
  {
    razao_social: 'Repsol Química S.A.',
    cif: 'A28005395',
    cnae_codigo: '2011',
    cnae_descricao: 'Fabricación de productos químicos básicos',
    setor: 'Industria Química & Petroquímica',
    provincia: 'Madrid / Tarragona / Ciudad Real / A Coruña',
    municipio: 'Madrid',
    endereco: 'Calle Méndez Álvaro, 44',
    website: 'https://www.repsol.com',
    email: 'quimica@repsol.com',
    telefone: '+34 901 101 101',
  },
  {
    razao_social: 'Cepsa Química S.A. (Moeve)',
    cif: 'A28003705',
    cnae_codigo: '2011',
    cnae_descricao: 'Petroquímica y derivados',
    setor: 'Industria Química & Petroquímica',
    provincia: 'Madrid / Cádiz / Huelva',
    municipio: 'Madrid',
    endereco: 'Paseo de la Castellana, 259A, Torre Cepsa',
    website: 'https://www.moeve.com',
    email: 'comunicacion@moeve.com',
    telefone: '+34 913 376 000',
  },
  {
    razao_social: 'Ercros S.A.',
    cif: 'A08000078',
    cnae_codigo: '2011',
    cnae_descricao: 'Química básica, derivados del cloro e intermedios',
    setor: 'Industria Química & Petroquímica',
    provincia: 'Barcelona / Tarragona / Huesca',
    municipio: 'Barcelona',
    endereco: 'Avinguda Diagonal, 593-595',
    website: 'https://www.ercros.es',
    email: 'ercros@ercros.es',
    telefone: '+34 934 393 009',
  },
  {
    razao_social: 'Fertiberia S.A.',
    cif: 'A28165298',
    cnae_codigo: '2015',
    cnae_descricao: 'Fabricación de fertilizantes y compuestos nitrogenados',
    setor: 'Industria Química & Petroquímica',
    provincia: 'Madrid / Huelva / Ciudad Real / Asturias',
    municipio: 'Madrid',
    endereco: 'Calle Agustín de Foxá, 27',
    website: 'https://www.fertiberia.com',
    email: 'fertiberia@fertiberia.es',
    telefone: '+34 915 866 200',
  },

  // ==========================================
  // CNAE 7112 / 3320 - INGENIERÍA EPC Y MONTAJES INDUSTRIALES
  // ==========================================
  {
    razao_social: 'Técnicas Reunidas S.A.',
    cif: 'A28092583',
    cnae_codigo: '7112',
    cnae_descricao: 'Servicios técnicos de ingeniería y proyectos EPC',
    setor: 'Ingeniería & Contratistas EPC',
    provincia: 'Madrid',
    municipio: 'Madrid',
    endereco: 'Avenida de Burgos, 89, Edificio Adequa 3',
    website: 'https://www.tecnicasreunidas.es',
    email: 'tr@tecnicasreunidas.es',
    telefone: '+34 915 920 300',
  },
  {
    razao_social: 'Sener Ingeniería y Sistemas S.A.',
    cif: 'A48016489',
    cnae_codigo: '7112',
    cnae_descricao: 'Servicios de ingeniería multidisciplinar',
    setor: 'Ingeniería & Contratistas EPC',
    provincia: 'Vizcaya / Madrid',
    municipio: 'Getxo',
    endereco: 'Severo Ochoa, 4, Parque Tecnológico de Bizkaia',
    website: 'https://www.group.sener',
    email: 'info@sener.es',
    telefone: '+34 944 817 500',
  },
  {
    razao_social: 'Ingeteam S.A.',
    cif: 'A48093892',
    cnae_codigo: '7112',
    cnae_descricao: 'Ingeniería eléctrica, generadores y convertidores',
    setor: 'Ingeniería & Contratistas EPC',
    provincia: 'Vizcaya / Navarra / Albacete',
    municipio: 'Zamudio',
    endereco: 'Parque Tecnológico de Bizkaia, Edificio 106',
    website: 'https://www.ingeteam.com',
    email: 'info@ingeteam.com',
    telefone: '+34 944 039 600',
  },
  {
    razao_social: 'Elecnor S.A.',
    cif: 'A48027056',
    cnae_codigo: '3320',
    cnae_descricao: 'Instalación de maquinaria y equipos industriales EPC',
    setor: 'Ingeniería & Contratistas EPC',
    provincia: 'Madrid / Vizcaya',
    municipio: 'Madrid',
    endereco: 'Paseo de la Castellana, 81',
    website: 'https://www.elecnor.com',
    email: 'elecnor@elecnor.com',
    telefone: '+34 914 179 900',
  },
  {
    razao_social: 'Imasa Ingeniería y Proyectos S.A.',
    cif: 'A33010976',
    cnae_codigo: '7112',
    cnae_descricao: 'Ingeniería, fabricación y montaje industrial',
    setor: 'Ingeniería & Contratistas EPC',
    provincia: 'Asturias / Madrid',
    municipio: 'Oviedo',
    endereco: 'Calle Asturias, 20',
    website: 'https://www.imasa.com',
    email: 'imasa@imasa.com',
    telefone: '+34 985 964 444',
  },
];

async function populateDb(dbName, connString) {
  const client = new Client({ connectionString: connString });
  await client.connect();

  console.log(`\n================ Populating Master Table in [${dbName}] ================`);

  // Get active empresa_id
  const empRes = await client.query('SELECT empresa_id FROM core_comercial.leads WHERE empresa_id IS NOT NULL LIMIT 1;');
  let empresaId = empRes.rows[0]?.empresa_id || 'bedbc2ad-bb7a-4bb3-986e-07224a9a5a3d';

  let inserted = 0;
  for (const emp of SPANISH_ENTERPRISES) {
    const res = await client.query(`
      INSERT INTO core_comercial.empresas_espanha_cnae (
        empresa_id, cif, razao_social, cnae_codigo, cnae_descricao, setor,
        provincia, municipio, endereco, website, email, email_status,
        telefone, status_enriquecimento, created_at, updated_at
      ) VALUES (
        $1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11, 'verificado_mx',
        $12, 'enriquecido', NOW(), NOW()
      ) ON CONFLICT DO NOTHING RETURNING id;
    `, [
      empresaId, emp.cif, emp.razao_social, emp.cnae_codigo, emp.cnae_descricao, emp.setor,
      emp.provincia, emp.municipio, emp.endereco, emp.website, emp.email,
      emp.telefone
    ]);
    if (res.rows.length > 0) inserted++;
  }

  const countRes = await client.query('SELECT count(*) FROM core_comercial.empresas_espanha_cnae;');
  console.log(`[${dbName}] Master table now has ${countRes.rows[0].count} official registered companies!`);

  await client.end();
}

async function run() {
  await populateDb('DEV', devConnectionString);
  await populateDb('PROD', prodConnectionString);
}

run();
