UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0045';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0045';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0045';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1085';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E1766';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0262';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0262';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0262';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0288';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0288';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0288';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1162';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1162';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E1955';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1364';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0935';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0612';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Alta' WHERE cod_colab = 'E0582';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0582';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0582';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0741';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0741';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0517';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0455';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0455';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0455';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0455';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0986';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0986';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0986';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0986';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0986';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0986';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1183';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0092';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1337';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1863';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E1863';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1005';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0690';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0767';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0767';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0972';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1323';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E1818';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1818';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1138';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1138';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1099';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'anulado' WHERE cod_colab = 'E1099';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1384';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1384';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1384';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1195';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1195';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1195';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0649';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'anulado' WHERE cod_colab = 'E0760';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0760';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0760';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'anulado' WHERE cod_colab = 'E1090';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0070';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E1810';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0762';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0762';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0762';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E1196';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1196';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1196';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0309';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0309';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0091';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0075';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0075';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1939';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1939';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'anulado' WHERE cod_colab = 'E0878';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0610';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0610';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0610';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1938';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1217';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0624';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0624';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E1847';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1847';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0007';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0007';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0007';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0007';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0007';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0007';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0007';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0928';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0928';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0701';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0700';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0700';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'anulado' WHERE cod_colab = 'E0700';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0700';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1047';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1047';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0234';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0520';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0520';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0520';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0520';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0520';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0520';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0723';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0266';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E1926';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0630';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0630';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0630';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0630';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1585';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1585';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1136';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E1831';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1718';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0493';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0296';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0296';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1357';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E1357';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1586';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1586';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1135';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1135';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1135';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1135';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0519';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0619';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0619';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'anulado' WHERE cod_colab = 'E0619';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0619';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0619';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0714';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0714';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0714';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0714';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0317';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0317';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0317';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1587';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1587';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1398';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E1398';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0809';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0809';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Alta' WHERE cod_colab = 'E0111';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0111';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0810';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0810';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0810';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0810';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0810';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0810';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0810';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0810';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0840';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1371';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1371';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E1653';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1653';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E1972';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E1788';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'anulado' WHERE cod_colab = 'E1288';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1288';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Alta' WHERE cod_colab = 'E0230';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0528';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0528';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0528';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0528';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0919';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'anulado' WHERE cod_colab = 'E0919';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0919';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0636';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E1739';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1739';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1739';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E1739';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E1739';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Alta' WHERE cod_colab = 'E0469';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0469';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0469';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0469';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0469';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0305';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0305';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0305';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0305';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0305';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0411';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0411';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0358';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'anulado' WHERE cod_colab = 'E0358';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0358';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0397';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E1830';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1134';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0589';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0589';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0589';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E2063';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E2063';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0633';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0633';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0633';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0930';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1235';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1235';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0032';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0032';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0032';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0032';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0239';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E1691';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0657';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0657';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0657';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0173';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0173';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0173';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0173';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0791';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0791';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0791';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0791';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0791';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0791';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0791';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0791';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E1945';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1378';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1225';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E1225';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0350';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0350';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0350';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0350';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0269';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0758';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E2064';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0822';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0822';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0354';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0405';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0405';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1060';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1060';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E1279';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1055';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1055';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1055';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1055';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1055';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Alta' WHERE cod_colab = 'E1055';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0192';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0192';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E0192';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E0192';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Baja' WHERE cod_colab = 'E1588';
UPDATE core_personal.workers SET status_trabajador = 'Activo', status_seguridad = 'Alta' WHERE cod_colab = 'E1707';
UPDATE core_personal.workers SET status_trabajador = 'Activo', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E0565';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E2137';
UPDATE core_personal.workers SET status_trabajador = 'Activo', status_seguridad = 'Pendiente Baja' WHERE cod_colab = 'E2050';
UPDATE core_personal.workers SET status_trabajador = 'Activo', status_seguridad = 'Alta' WHERE cod_colab = 'E2131';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E1824';
UPDATE core_personal.workers SET status_trabajador = 'Activo', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E1961';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Alta' WHERE cod_colab = 'E2144';
UPDATE core_personal.workers SET status_trabajador = 'Activo', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E2106';
UPDATE core_personal.workers SET status_trabajador = 'Activo', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E2112';
UPDATE core_personal.workers SET status_trabajador = 'Activo', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E2143';
UPDATE core_personal.workers SET status_trabajador = 'Activo', status_seguridad = 'Alta' WHERE cod_colab = 'E0462';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E2138';
UPDATE core_personal.workers SET status_trabajador = 'Activo', status_seguridad = 'Alta' WHERE cod_colab = 'E1939';
UPDATE core_personal.workers SET status_trabajador = 'Activo', status_seguridad = 'Pendiente Baja' WHERE cod_colab = 'E0358';
UPDATE core_personal.workers SET status_trabajador = 'Activo', status_seguridad = 'Alta' WHERE cod_colab = 'E1055';
UPDATE core_personal.workers SET status_trabajador = 'Activo', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E2139';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Alta' WHERE cod_colab = 'E1811';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E1810';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Alta' WHERE cod_colab = 'E0262';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E1769';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E2056';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E1709';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Alta' WHERE cod_colab = 'E0279';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E1072';
UPDATE core_personal.workers SET status_trabajador = 'Activo', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E2146';
UPDATE core_personal.workers SET status_trabajador = 'Activo', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E0560';
UPDATE core_personal.workers SET status_trabajador = 'Activo', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E0487';
UPDATE core_personal.workers SET status_trabajador = 'Activo', status_seguridad = 'Alta' WHERE cod_colab = 'E0399';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E1857';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E0490';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E2141';
UPDATE core_personal.workers SET status_trabajador = 'Inactivo', status_seguridad = 'Anulado' WHERE cod_colab = 'E1930';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Alta' WHERE cod_colab = 'E1151';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E1992';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E1525';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E2065';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Alta' WHERE cod_colab = 'E1649';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E2058';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E1741';
UPDATE core_personal.workers SET status_trabajador = 'Activo', status_seguridad = 'Alta' WHERE cod_colab = 'E1776';
UPDATE core_personal.workers SET status_trabajador = 'Activo', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E1820';
UPDATE core_personal.workers SET status_trabajador = 'Activo', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E0310';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E2148';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Alta' WHERE cod_colab = 'E0704';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Alta' WHERE cod_colab = 'E1469';
UPDATE core_personal.workers SET status_trabajador = 'Activo', status_seguridad = 'Alta' WHERE cod_colab = 'E1117';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Alta' WHERE cod_colab = 'E1764';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Alta' WHERE cod_colab = 'E2151';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Alta' WHERE cod_colab = 'E2153';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Pendiente Alta' WHERE cod_colab = 'E1540';
UPDATE core_personal.workers SET status_trabajador = 'Pendiente Ingresar', status_seguridad = 'Alta' WHERE cod_colab = 'E1912';
UPDATE core_personal.workers SET status_trabajador = 'Activo', status_seguridad = 'Alta' WHERE cod_colab = 'E0303';
UPDATE core_personal.seguridade_status
    SELECT id FROM core_personal.workers 
INSERT INTO core_personal.seguridade_status (empresa_id, worker_id, tipo_evento, status, origem, data_solicitacao)
SELECT empresa_id, id, 'alta', 'pendente', 'Importação Excel', NOW()
      SELECT 1 FROM core_personal.seguridade_status ss 
INSERT INTO core_personal.seguridade_status (empresa_id, worker_id, tipo_evento, status, origem, data_solicitacao)
SELECT empresa_id, id, 'baixa', 'pendente', 'Importação Excel', NOW()
      SELECT 1 FROM core_personal.seguridade_status ss 
