UPDATE core_personal.workers SET nome = 'ADRIAN CARLOSAMA CHAVEZ', pasaporte = 'AY871309' WHERE cod_colab = 'E0452';
UPDATE core_personal.workers SET nome = 'ALAN FRANCISCO NAVAS DIAZ', pasaporte = 'BD749809' WHERE cod_colab = 'E0194';
UPDATE core_personal.workers SET nome = 'ALAN GERSON RAMIREZ ACARO', pasaporte = '120655378' WHERE cod_colab = 'E0406';
UPDATE core_personal.workers SET nome = 'ALBEIRO CARDOZO HEREDIA', pasaporte = 'AY405605' WHERE cod_colab = 'E1402';
UPDATE core_personal.workers SET nome = 'ALBEIRO OBANDO MICOLTA', pasaporte = 'BD593560' WHERE cod_colab = 'E0272';
UPDATE core_personal.workers SET nome = 'ALBERTO ISMAEL MENDIETA CACERES', pasaporte = '122134064' WHERE cod_colab = 'E0449';
UPDATE core_personal.workers SET nome = 'ALBERTO LUIS MALDONADO BARRERA', pasaporte = 'AY305422' WHERE cod_colab = 'E1448';
UPDATE core_personal.workers SET nome = 'ALEJANDRO JOSE BORJA MANGA', pasaporte = 'BE511135' WHERE cod_colab = 'E0128';
UPDATE core_personal.workers SET nome = 'ALEX DAVID GOMEZ VILLADA', pasaporte = 'AW58954' WHERE cod_colab = 'E0388';
UPDATE core_personal.workers SET nome = 'ALEX MAURICIO CARDONA RAMIREZ', pasaporte = 'BE848923' WHERE cod_colab = 'E0593';
UPDATE core_personal.workers SET nome = 'ALEXANDER ANTHONY ZAMORA ALMENDARIZ', pasaporte = '124688504' WHERE cod_colab = 'E0362';
UPDATE core_personal.workers SET nome = 'ALEXANDER GUZMAN', pasaporte = 'AS735626' WHERE cod_colab = 'E2098';
UPDATE core_personal.workers SET nome = 'ALEXANDER MANUEL LOPEZ ROJAS', pasaporte = 'AV692233' WHERE cod_colab = 'E0386';
UPDATE core_personal.workers SET nome = 'ALEXANDER PEREIRA HERNANDEZ', pasaporte = 'BD874725' WHERE cod_colab = 'E1684';
UPDATE core_personal.workers SET nome = 'ALIRIO ORTIZ MOLINA', pasaporte = 'BE28620' WHERE cod_colab = 'E0254';
UPDATE core_personal.workers SET nome = 'ALVARO ARIZA CONTRERAS', pasaporte = 'BE168542' WHERE cod_colab = 'E1707';
UPDATE core_personal.workers SET nome = 'ALVARO ENRIQUE ROJAS DE LA OSSA', pasaporte = 'AQ520819' WHERE cod_colab = 'E0166';
UPDATE core_personal.workers SET nome = 'ALVARO FIGUEROA ARANGO', pasaporte = 'BF806838' WHERE cod_colab = 'E0565';
UPDATE core_personal.workers SET nome = 'ALVARO JAVIER NARVAEZ MUÑOZ', pasaporte = 'BD516455' WHERE cod_colab = 'E2079';
UPDATE core_personal.workers SET nome = 'ANDERSON CHELUVAY GONZALEZ TRUJILLO', pasaporte = 'AY076491' WHERE cod_colab = 'E1703';
UPDATE core_personal.workers SET nome = 'ANDRES ALEXANDER BEJARANO PEREZ', pasaporte = 'BG383525' WHERE cod_colab = 'E1891';
UPDATE core_personal.workers SET nome = 'ANDRES CAMILO ALVAREZ CUERVO', pasaporte = 'BD487431' WHERE cod_colab = 'E0500';
UPDATE core_personal.workers SET nome = 'ANDRES FELIPE GOMEZ PUERTA', pasaporte = 'AY694983' WHERE cod_colab = 'E0359';
UPDATE core_personal.workers SET nome = 'ANDRES FELIPE LOPEZ FONTALVO', pasaporte = 'BC345878' WHERE cod_colab = 'E1406';
UPDATE core_personal.workers SET nome = 'ANDRES FELIPE PULIDO GOMEZ', pasaporte = 'BF917906' WHERE cod_colab = 'E1888';
UPDATE core_personal.workers SET nome = 'ANDRIGK EDILBERTO CARDENAS SUAREZ', pasaporte = 'AX870283' WHERE cod_colab = 'E0529';
UPDATE core_personal.workers SET nome = 'ANDY LYONEL CARRASCO VARGAS', pasaporte = '123640273' WHERE cod_colab = 'E0487';
UPDATE core_personal.workers SET nome = 'ANGEL ANDRES BARDALES RAMIREZ', pasaporte = '124965116' WHERE cod_colab = 'E1453';
UPDATE core_personal.workers SET nome = 'ANGEL TEHERAN CARABALLO', pasaporte = 'AS491762' WHERE cod_colab = 'E1454';
UPDATE core_personal.workers SET nome = 'ANSONY RODRIGUEZ PORRAS', pasaporte = 'BD082611' WHERE cod_colab = 'E0625';
UPDATE core_personal.workers SET nome = 'ANTONIO FAGNER ARAUJO DE OLIVEIRA', pasaporte = 'GC832324' WHERE cod_colab = 'E2126';
UPDATE core_personal.workers SET nome = 'ANUAR JIMENEZ DELGADO', pasaporte = 'BG111658' WHERE cod_colab = 'E1801';
UPDATE core_personal.workers SET nome = 'APOLINAR GARCIA HERNANDEZ', pasaporte = 'BH153822' WHERE cod_colab = 'E2073';
UPDATE core_personal.workers SET nome = 'ARLEMAR RAFAEL CAMPOS WOLFF', pasaporte = '172294076' WHERE cod_colab = 'E0383';
UPDATE core_personal.workers SET nome = 'ARLEY DARIO PANTOJA CABRERA', pasaporte = 'BE394505' WHERE cod_colab = 'E0177';
UPDATE core_personal.workers SET nome = 'ARLEY GUTIERREZ CORREDOR', pasaporte = 'BD565193' WHERE cod_colab = 'E1723';
UPDATE core_personal.workers SET nome = 'ARMANDO DENIS ENRIQUEZ BLAS', pasaporte = '124783559' WHERE cod_colab = 'E0401';
UPDATE core_personal.workers SET nome = 'ARMANDO QUIROGA JOVEN', pasaporte = 'AV579253' WHERE cod_colab = 'E1790';
UPDATE core_personal.workers SET nome = 'ARNULFO SANCHEZ RUEDA', pasaporte = 'BG003645' WHERE cod_colab = 'E1457';
UPDATE core_personal.workers SET nome = 'AYRTON MAXIMO CUMPA SENADOR', pasaporte = '124908115' WHERE cod_colab = 'E0062';
UPDATE core_personal.workers SET nome = 'BAIRON RENE BURBANO MORALES', pasaporte = 'BH390405' WHERE cod_colab = 'E1590';
UPDATE core_personal.workers SET nome = 'BLADIMIRO DIAZ MARTINEZ', pasaporte = 'BD982354' WHERE cod_colab = 'E0195';
UPDATE core_personal.workers SET nome = 'BLAKIS ANTONIO BARBOZA TRUJILLO', pasaporte = 'BD964686' WHERE cod_colab = 'E1842';
UPDATE core_personal.workers SET nome = 'BOLIVAR GABRIEL ALDANA RAMIREZ', pasaporte = 'BE190764' WHERE cod_colab = 'E2103';
UPDATE core_personal.workers SET nome = 'BORIS ALI CHUNGA LUJAN', pasaporte = '123498354' WHERE cod_colab = 'E0250';
UPDATE core_personal.workers SET nome = 'BRANDON RAMIREZ ZAPATA', pasaporte = 'BG012266' WHERE cod_colab = 'E1979';
UPDATE core_personal.workers SET nome = 'BRAYAN JOSE ALARCON MORALES', pasaporte = 'BG482312' WHERE cod_colab = 'E1897';
UPDATE core_personal.workers SET nome = 'BRAYAN JOSE SALINAS MARTINEZ', pasaporte = 'BA629221' WHERE cod_colab = 'E1668';
UPDATE core_personal.workers SET nome = 'BREINER MOLINA PELAEZ', pasaporte = 'AZ062652' WHERE cod_colab = 'E0622';
UPDATE core_personal.workers SET nome = 'BYRON YESID SUAREZ CUADRADO', pasaporte = 'BF203713' WHERE cod_colab = 'E2094';
UPDATE core_personal.workers SET nome = 'CAIO RENAN BARBOSA DA SILVA', pasaporte = 'YD083848' WHERE cod_colab = 'E2155';
UPDATE core_personal.workers SET nome = 'CAMILO ANDRES DUEÑAS NIÑO', pasaporte = 'AY619580' WHERE cod_colab = 'E1459';
UPDATE core_personal.workers SET nome = 'CAMILO ANDRES RUBIO LEON', pasaporte = 'AW659299' WHERE cod_colab = 'E1995';
UPDATE core_personal.workers SET nome = 'CARLOS ADRIAN CAMELO CALDERON', pasaporte = 'AV777079' WHERE cod_colab = 'E0152';
UPDATE core_personal.workers SET nome = 'CARLOS ALBERTO RAMOS URBANO', pasaporte = 'BF815179' WHERE cod_colab = 'E0155';
UPDATE core_personal.workers SET nome = 'CARLOS ANDRES ARROYO BERTEL', pasaporte = 'BD878641' WHERE cod_colab = 'E2020';
UPDATE core_personal.workers SET nome = 'CARLOS ANDRES JIMENEZ RAMIREZ', pasaporte = 'AQ838256' WHERE cod_colab = 'E0396';
UPDATE core_personal.workers SET nome = 'CARLOS ANDRES MANTILLA URREGO', pasaporte = 'AT366466' WHERE cod_colab = 'E1407';
UPDATE core_personal.workers SET nome = 'CARLOS ANDRES PULIDO CHAVEZ', pasaporte = 'BE316400' WHERE cod_colab = 'E1731';
UPDATE core_personal.workers SET nome = 'CARLOS ANDRES SILVA CORREA', pasaporte = 'AW284218' WHERE cod_colab = 'E2026';
UPDATE core_personal.workers SET nome = 'CARLOS ARTURO GONZALEZ GOMEZ', pasaporte = 'BE784998' WHERE cod_colab = 'E0100';
UPDATE core_personal.workers SET nome = 'CARLOS AUGUSTO SALDARRIAGA MONTEALBAN', pasaporte = '224482572' WHERE cod_colab = 'E0402';
UPDATE core_personal.workers SET nome = 'CARLOS DANIEL RODRIGUEZ PENA', pasaporte = 'BE392017' WHERE cod_colab = 'E1976';
UPDATE core_personal.workers SET nome = 'CARLOS EDUARDO CARDENAS ESPINOSA', pasaporte = 'BC201112' WHERE cod_colab = 'E0144';
UPDATE core_personal.workers SET nome = 'CARLOS JESUS MENDIGUETE VILLA', pasaporte = '122371760' WHERE cod_colab = 'E1465';
UPDATE core_personal.workers SET nome = 'CARLOS JULIO ACOSTA CAMACHO', pasaporte = 'AZ347415' WHERE cod_colab = 'E0553';
UPDATE core_personal.workers SET nome = 'CARLOS JULIO LOZANO SIERRA', pasaporte = 'AZ527939' WHERE cod_colab = 'E1854';
UPDATE core_personal.workers SET nome = 'CARLOS MARIO JARAMILLO LOPEZ', pasaporte = 'AV385391' WHERE cod_colab = 'E0491';
UPDATE core_personal.workers SET nome = 'CARLOS MARIO ROCHA ARIZ', pasaporte = 'BA866770' WHERE cod_colab = 'E2054';
UPDATE core_personal.workers SET nome = 'CARLOS URIEL CASTRO NIEVA', pasaporte = 'BD302792' WHERE cod_colab = 'E0797';
UPDATE core_personal.workers SET nome = 'CESAR AUGUSTO ANGARITA RIVERA', pasaporte = 'BC804892' WHERE cod_colab = 'E1982';
UPDATE core_personal.workers SET nome = 'CESAR EDUARDO RAMIREZ TOVAR', pasaporte = 'BH257842' WHERE cod_colab = 'E2050';
UPDATE core_personal.workers SET nome = 'CESAR NORBEY PENAGOS DUQUE', pasaporte = 'BH278670' WHERE cod_colab = 'E2120';
UPDATE core_personal.workers SET nome = 'CICERO LIMA BATISTA', pasaporte = 'FU806455' WHERE cod_colab = 'E1129';
UPDATE core_personal.workers SET nome = 'CLAUDEMIR DO NASCIMENTO FURTADO', pasaporte = 'GA370662' WHERE cod_colab = 'E2131';
UPDATE core_personal.workers SET nome = 'CRISTIAN ADRIAN QUIROS RAMOS', pasaporte = 'PA1303403' WHERE cod_colab = 'E1776';
UPDATE core_personal.workers SET nome = 'CRISTIAN ARIZA MARTINEZ', pasaporte = 'AV770384' WHERE cod_colab = 'E1909';
UPDATE core_personal.workers SET nome = 'CRISTIAN CAMILO BORRE SILVA', pasaporte = 'BG774596' WHERE cod_colab = 'E1918';
UPDATE core_personal.workers SET nome = 'DAMIAN ZAMBRANO TULANDE', pasaporte = 'AX016404' WHERE cod_colab = 'E1895';
UPDATE core_personal.workers SET nome = 'DANIEL DOMINGO MARCHENA AGURTO', pasaporte = '122476282' WHERE cod_colab = 'E0303';
UPDATE core_personal.workers SET nome = 'DANIER CALDERON SALAS', pasaporte = 'BG974482' WHERE cod_colab = 'E1853';
UPDATE core_personal.workers SET nome = 'DANILO PINEDA RIVAS', pasaporte = 'PA0882805' WHERE cod_colab = 'E1471';
UPDATE core_personal.workers SET nome = 'DARIO CARLOS MANUEL PEREIRA', pasaporte = 'N2728314' WHERE cod_colab = 'E1663';
UPDATE core_personal.workers SET nome = 'DARWIN JOSE VASQUEZ ORTEGA', pasaporte = '122668383' WHERE cod_colab = 'E0592';
UPDATE core_personal.workers SET nome = 'DAVID GUSTAVO DE LOS ANGELES PATIÑO RAMOS', pasaporte = 'AW458316' WHERE cod_colab = 'E0403';
UPDATE core_personal.workers SET nome = 'DAVID RICARDO SANCHEZ ZAPATA', pasaporte = '124650623' WHERE cod_colab = 'E0083';
UPDATE core_personal.workers SET nome = 'DEWIN DE JESUS DE LEON BARRERA', pasaporte = 'BD239523' WHERE cod_colab = 'E2021';
UPDATE core_personal.workers SET nome = 'DIDIER JOSE CHOLES MIRANDA', pasaporte = 'BF490621' WHERE cod_colab = 'E0613';
UPDATE core_personal.workers SET nome = 'DIEGO ROBERTO SOUZA SCAVACINI', pasaporte = 'GA008817' WHERE cod_colab = 'E0578';
UPDATE core_personal.workers SET nome = 'DOMINGO RAMON VEGA HUMANEZ', pasaporte = 'BD711341' WHERE cod_colab = 'E1826';
UPDATE core_personal.workers SET nome = 'DUAN ANTONIO AVILA NORIEGA', pasaporte = 'BD237295' WHERE cod_colab = 'E0356';
UPDATE core_personal.workers SET nome = 'DUMAR EFREN RAMIREZ MENDOZA', pasaporte = 'BH448648' WHERE cod_colab = 'E1148';
UPDATE core_personal.workers SET nome = 'DUVAN ALEXIS SUAREZ TRUJILLO', pasaporte = 'BG659846' WHERE cod_colab = 'E2134';
UPDATE core_personal.workers SET nome = 'EDDIE DE JESUS ZARATE IGUARAN', pasaporte = 'BG744554' WHERE cod_colab = 'E1970';
UPDATE core_personal.workers SET nome = 'EDGAR CORRALES HOYOS', pasaporte = 'AU803778' WHERE cod_colab = 'E2090';
UPDATE core_personal.workers SET nome = 'EDGAR ENRIQUE TORRES RAMIREZ', pasaporte = '123970265' WHERE cod_colab = 'E1868';
UPDATE core_personal.workers SET nome = 'EDILBERTO DOMINGUEZ PEREIRA', pasaporte = 'AS480654' WHERE cod_colab = 'E0161';
UPDATE core_personal.workers SET nome = 'EDILSON TORRES SALCEDO', pasaporte = 'BG874595' WHERE cod_colab = 'E1806';
UPDATE core_personal.workers SET nome = 'EDINSON LOZANO TELLEZ', pasaporte = 'BE186995' WHERE cod_colab = 'E0984';
UPDATE core_personal.workers SET nome = 'EDU PANDURO RUIZ', pasaporte = '124554632' WHERE cod_colab = 'E0106';
UPDATE core_personal.workers SET nome = 'EDUAR MANUEL DAVILA CERON', pasaporte = 'BD233738' WHERE cod_colab = 'E0637';
UPDATE core_personal.workers SET nome = 'EDUARD YOVANNY LOZANO OSORIO', pasaporte = 'BE510629' WHERE cod_colab = 'E0363';
UPDATE core_personal.workers SET nome = 'EDUARDO JOSE RUSSO LINERO', pasaporte = 'BC862773' WHERE cod_colab = 'E0107';
UPDATE core_personal.workers SET nome = 'EDWAR ANDRES BENACHI ARCE', pasaporte = 'AT564771' WHERE cod_colab = 'E0257';
UPDATE core_personal.workers SET nome = 'EDWAR ARIEL VELEZ POSADA', pasaporte = 'BC510407' WHERE cod_colab = 'E1412';
UPDATE core_personal.workers SET nome = 'EDWARD IGNACIO DIAZ AVILA', pasaporte = 'BC426669' WHERE cod_colab = 'E0507';
UPDATE core_personal.workers SET nome = 'EDWIN ALBERTO CABRERA AGUILAR', pasaporte = 'BG219450' WHERE cod_colab = 'E1484';
UPDATE core_personal.workers SET nome = 'EDWIN ALEXANDER DIAZ PITRE', pasaporte = 'AT800138' WHERE cod_colab = 'E0232';
UPDATE core_personal.workers SET nome = 'EDWIN ALFONSO ORTIZ DELGADO', pasaporte = '125441645' WHERE cod_colab = 'E1907';
UPDATE core_personal.workers SET nome = 'EDWIN BERNAL ARCINIEGAS', pasaporte = 'BE755309' WHERE cod_colab = 'E1485';
UPDATE core_personal.workers SET nome = 'EDWIN CASTANEDA HENAO', pasaporte = 'BG026315' WHERE cod_colab = 'E1787';
UPDATE core_personal.workers SET nome = 'EDWIN DIAZ MARULANDA', pasaporte = 'AS696648' WHERE cod_colab = 'E0364';
UPDATE core_personal.workers SET nome = 'EDWIN FERNANDO LINARES MACA', pasaporte = 'AW519147' WHERE cod_colab = 'E0180';
UPDATE core_personal.workers SET nome = 'EISON SALAS AHUMEDO', pasaporte = 'BF023432' WHERE cod_colab = 'E0233';
UPDATE core_personal.workers SET nome = 'ELKIN ARMANDO GARZON LOPEZ', pasaporte = 'AZ662731' WHERE cod_colab = 'E0873';
UPDATE core_personal.workers SET nome = 'EMILIANO CUADROS LAGUADO', pasaporte = 'AX135406' WHERE cod_colab = 'E0407';
UPDATE core_personal.workers SET nome = 'ENRI JAIME CALDAS BERMUDES', pasaporte = '124087149' WHERE cod_colab = 'E0424';
UPDATE core_personal.workers SET nome = 'ENRIQUE RUBIANO AGUDELO', pasaporte = 'BD664243' WHERE cod_colab = 'E1857';
UPDATE core_personal.workers SET nome = 'ERIK CHARLY GOMEZ RIOS', pasaporte = '124959884' WHERE cod_colab = 'E1268';
UPDATE core_personal.workers SET nome = 'ERIK RUBEN RAMIREZ SIMANCAS', pasaporte = 'AU419727' WHERE cod_colab = 'E1117';
UPDATE core_personal.workers SET nome = 'ERNESTO GERMAN HERRERA', pasaporte = 'AAH381134' WHERE cod_colab = 'E1713';
UPDATE core_personal.workers SET nome = 'ESTEBAN DARIO ACOSTA MARTINEZ', pasaporte = 'BF919018' WHERE cod_colab = 'E0006';
UPDATE core_personal.workers SET nome = 'EVELIO ANGULO ANGULO', pasaporte = 'BD539122' WHERE cod_colab = 'E0125';
UPDATE core_personal.workers SET nome = 'FABIAN ANDRES BERNAL MONTENEGRO', pasaporte = 'BE117627' WHERE cod_colab = 'E1194';
UPDATE core_personal.workers SET nome = 'FABIAN ARTURO RUIZ GARCIA', pasaporte = 'BE808642' WHERE cod_colab = 'E0389';
UPDATE core_personal.workers SET nome = 'FABIAN JARAMILLO MARIN', pasaporte = 'BG051966' WHERE cod_colab = 'E0632';
UPDATE core_personal.workers SET nome = 'FABIAN LEONARDO CERON VALENCIA', pasaporte = 'AY595372' WHERE cod_colab = 'E0890';
UPDATE core_personal.workers SET nome = 'FABIAN LLERAR ROA MATEUS', pasaporte = 'BF667496' WHERE cod_colab = 'E0235';
UPDATE core_personal.workers SET nome = 'FABIO DOMINGUEZ BRAVO', pasaporte = 'AX758453' WHERE cod_colab = 'E1932';
UPDATE core_personal.workers SET nome = 'FARID JOSE ROJAS GUERRA', pasaporte = 'AW775868' WHERE cod_colab = 'E2052';
UPDATE core_personal.workers SET nome = 'FELIPE OQUENDO CALLEJAS', pasaporte = 'BC404757' WHERE cod_colab = 'E1492';
UPDATE core_personal.workers SET nome = 'FERNANDO ANTONIO CARDENAS CARDENAS', pasaporte = 'BH171655' WHERE cod_colab = 'E2033';
UPDATE core_personal.workers SET nome = 'FERNEY ALEXANDER VARGAS SERRANO', pasaporte = 'AV984921' WHERE cod_colab = 'E2082';
UPDATE core_personal.workers SET nome = 'FRANCISCO JAVIER MERCADO MELENDEZ', pasaporte = 'BF307871' WHERE cod_colab = 'E0229';
UPDATE core_personal.workers SET nome = 'FRANK ESNEIDER PEREZ TABARES', pasaporte = 'BA181068' WHERE cod_colab = 'E1832';
UPDATE core_personal.workers SET nome = 'FRANKLIN JOSE DIAZ LINCE', pasaporte = 'AZ056980' WHERE cod_colab = 'E2115';
UPDATE core_personal.workers SET nome = 'FRANKLYN OMAR DE LA CRUZ SERNAQUE', pasaporte = '124910690' WHERE cod_colab = 'E1948';
UPDATE core_personal.workers SET nome = 'FREDDY ANDRES BAYONA CASTRO', pasaporte = 'BH162372' WHERE cod_colab = 'E1856';
UPDATE core_personal.workers SET nome = 'FREDERICK AU BLANQUICETT', pasaporte = 'AT154012' WHERE cod_colab = 'E1911';
UPDATE core_personal.workers SET nome = 'FREDIS ANTONIO MORELOS COLON', pasaporte = 'BE962974' WHERE cod_colab = 'E0414';
UPDATE core_personal.workers SET nome = 'FREDIS BOLAÑOS GARCIA', pasaporte = 'AU9055718' WHERE cod_colab = 'E1496';
UPDATE core_personal.workers SET nome = 'FREDY ALEXANDER GOMEZ CORTES', pasaporte = 'AZ806528' WHERE cod_colab = 'E1497';
UPDATE core_personal.workers SET nome = 'FREDY JAVIER CCALLA ROJAS', pasaporte = '122449526' WHERE cod_colab = 'E0237';
UPDATE core_personal.workers SET nome = 'FREDY MANCERA URIBE', pasaporte = 'AW852982' WHERE cod_colab = 'E0394';
UPDATE core_personal.workers SET nome = 'FREDY RICARDO AGUDELO SALAMANCA', pasaporte = 'BG348049' WHERE cod_colab = 'E1699';
UPDATE core_personal.workers SET nome = 'GABRIEL VICTOR DE OLIVEIRA', pasaporte = 'FY360906' WHERE cod_colab = 'E2152';
UPDATE core_personal.workers SET nome = 'GERARDO LARA GONZALEZ', pasaporte = 'AZ350154' WHERE cod_colab = 'E2024';
UPDATE core_personal.workers SET nome = 'GERMAN GASPAR GODOY', pasaporte = 'AAH092004' WHERE cod_colab = 'E0571';
UPDATE core_personal.workers SET nome = 'GERSON STEVENS BELTRAN CASTELLANOS', pasaporte = 'BF979529' WHERE cod_colab = 'E1500';
UPDATE core_personal.workers SET nome = 'GIAN CARLOS SAAVEDRA LAPA', pasaporte = '122112465' WHERE cod_colab = 'E0197';
UPDATE core_personal.workers SET nome = 'GILBER MORA DIAZ', pasaporte = 'BE533838' WHERE cod_colab = 'E0104';
UPDATE core_personal.workers SET nome = 'GONZALO ARIEL NAVARRO', pasaporte = 'AAF976893' WHERE cod_colab = 'E0094';
UPDATE core_personal.workers SET nome = 'GONZALO QUINTANA PIMIENTO', pasaporte = 'AV974864' WHERE cod_colab = 'E1216';
UPDATE core_personal.workers SET nome = 'GRAVIEL ISIDRO DIAZ OROPEZA', pasaporte = '176533263' WHERE cod_colab = 'E1502';
UPDATE core_personal.workers SET nome = 'GUBERNEY HURTADO SAUCEDO', pasaporte = 'BE765534' WHERE cod_colab = 'E1151';
UPDATE core_personal.workers SET nome = 'GUERMAIN ISAAC SAJAMIN PANDURO', pasaporte = '123269924' WHERE cod_colab = 'E0035';
UPDATE core_personal.workers SET nome = 'GUILLERMO ARCINIEGAS MURILLO', pasaporte = 'BD835107' WHERE cod_colab = 'E0387';
UPDATE core_personal.workers SET nome = 'GUILLERMO LEON POSADA LONDONO', pasaporte = 'BF603422' WHERE cod_colab = 'E0151';
UPDATE core_personal.workers SET nome = 'GUSTAVO ADOLFO DEL ANGEL MONTERO', pasaporte = 'N06484260' WHERE cod_colab = 'E2105';
UPDATE core_personal.workers SET nome = 'GUSTAVO ANDRES PORRAS MORALES', pasaporte = 'BF160063' WHERE cod_colab = 'E1829';
UPDATE core_personal.workers SET nome = 'GUSTAVO DAMIAN DONOSO', pasaporte = 'AAH720600' WHERE cod_colab = 'E0089';
UPDATE core_personal.workers SET nome = 'GUSTAVO RAFAEL CARRILLO NUNEZ', pasaporte = 'BE664524' WHERE cod_colab = 'E1965';
UPDATE core_personal.workers SET nome = 'HANNER STIVEN GUZMAN PENCUA', pasaporte = 'BC579554' WHERE cod_colab = 'E1503';
UPDATE core_personal.workers SET nome = 'HAROLD REFERTIN SERNAQUE CARRASCO', pasaporte = '122168657' WHERE cod_colab = 'E0251';
UPDATE core_personal.workers SET nome = 'HARRIS HUMBERTO MENDOZA ANGULO', pasaporte = 'BG117089' WHERE cod_colab = 'E1504';
UPDATE core_personal.workers SET nome = 'HAYDER RAFAEL DIAZ MANAURE', pasaporte = '176850678' WHERE cod_colab = 'E2076';
UPDATE core_personal.workers SET nome = 'HECTOR DAVID RAMOS BUHEZO', pasaporte = '122564005' WHERE cod_colab = 'E0086';
UPDATE core_personal.workers SET nome = 'HECTOR FABIO GUZMAN CAICEDO', pasaporte = 'BG173317' WHERE cod_colab = 'E1615';
UPDATE core_personal.workers SET nome = 'HECTOR FABIO MAHETE CEDEÑO', pasaporte = 'AZ190036' WHERE cod_colab = 'E0557';
UPDATE core_personal.workers SET nome = 'HECTOR FABIO VASQUEZ MAYORGA', pasaporte = 'AU535352' WHERE cod_colab = 'E1074';
UPDATE core_personal.workers SET nome = 'HECTOR GIOVANNI MORENO SUSA', pasaporte = 'BC642342' WHERE cod_colab = 'E0274';
UPDATE core_personal.workers SET nome = 'HECTOR JAUMEN GUEVARA FORERO', pasaporte = 'BA488496' WHERE cod_colab = 'E1990';
UPDATE core_personal.workers SET nome = 'HECTOR LUIS PARRAGA ZAVALA', pasaporte = '124801216' WHERE cod_colab = 'E0240';
UPDATE core_personal.workers SET nome = 'HECTOR MANUEL BUELVAS ZAMBRANO', pasaporte = 'AZ172333' WHERE cod_colab = 'E2083';
UPDATE core_personal.workers SET nome = 'HECTOR SANCHEZ GUERRERO', pasaporte = 'BF505231' WHERE cod_colab = 'E0087';
UPDATE core_personal.workers SET nome = 'HELMER STIWAR MONTAÑA', pasaporte = 'BE317576' WHERE cod_colab = 'E1506';
UPDATE core_personal.workers SET nome = 'HELMUT WALTER ROSALES MURILLO', pasaporte = 'BF928317' WHERE cod_colab = 'E0431';
UPDATE core_personal.workers SET nome = 'HENRRY CASTRO COLLACHAGUA', pasaporte = '123949560' WHERE cod_colab = 'E0058';
UPDATE core_personal.workers SET nome = 'HENRY ALEXANDER RAMIREZ', pasaporte = 'BG904860' WHERE cod_colab = 'E1306';
UPDATE core_personal.workers SET nome = 'HENRY MARTINEZ CABEZAS', pasaporte = 'BD872694' WHERE cod_colab = 'E1999';
UPDATE core_personal.workers SET nome = 'HERNAN ALONSO CONTRERAS MARROQUIN', pasaporte = 'AS552560' WHERE cod_colab = 'E1507';
UPDATE core_personal.workers SET nome = 'HERNAN BERNARDO QUINTERO JARAMILLO', pasaporte = 'BD730030' WHERE cod_colab = 'E2070';
UPDATE core_personal.workers SET nome = 'HERNAN GERONIMO ALEJANDRO TARAZONA', pasaporte = '123259906' WHERE cod_colab = 'E0300';
UPDATE core_personal.workers SET nome = 'HERNAN RODRIGUEZ CUY', pasaporte = 'AY323956' WHERE cod_colab = 'E0501';
UPDATE core_personal.workers SET nome = 'HERNANDO AUGUSTO GALINDO GOMEZ', pasaporte = 'AX321519' WHERE cod_colab = 'E0408';
UPDATE core_personal.workers SET nome = 'HERNANDO ENRIQUE MAESTRE CASTILLA', pasaporte = 'BD293773' WHERE cod_colab = 'E1958';
UPDATE core_personal.workers SET nome = 'HUERLIN MANGLIO ALVARADO GUZMÁN', pasaporte = '122144587' WHERE cod_colab = 'E1509';
UPDATE core_personal.workers SET nome = 'HUMBERTO ENRIQUE MARTINEZ', pasaporte = 'BD961488' WHERE cod_colab = 'E0466';
UPDATE core_personal.workers SET nome = 'ISAHAC EMILIO RADA BRUGES', pasaporte = 'BF100511' WHERE cod_colab = 'E1618';
UPDATE core_personal.workers SET nome = 'ISAIAS MUNOZ MACHADO', pasaporte = 'BF343684' WHERE cod_colab = 'E0365';
UPDATE core_personal.workers SET nome = 'ISMAEL MENDEZ GAITAN', pasaporte = 'BG972717' WHERE cod_colab = 'E1992';
UPDATE core_personal.workers SET nome = 'ISRAEL BENAVIDES PRECIADO', pasaporte = 'BA377442' WHERE cod_colab = 'E0238';
UPDATE core_personal.workers SET nome = 'IVAN ANDRES ORTIZ GALVAN', pasaporte = 'BF743548' WHERE cod_colab = 'E2028';
UPDATE core_personal.workers SET nome = 'IVAN PRADA LOPEZ', pasaporte = 'BA925941' WHERE cod_colab = 'E0033';
UPDATE core_personal.workers SET nome = 'JAHIR SURLEY DELGADO AGREDO', pasaporte = 'BD471224' WHERE cod_colab = 'E0112';
UPDATE core_personal.workers SET nome = 'JAIME ALEJANDRO RETIS TOLENTINO', pasaporte = '123539902' WHERE cod_colab = 'E0587';
UPDATE core_personal.workers SET nome = 'JAIME HERNAN ARANGO MONSALVE', pasaporte = 'AY631349' WHERE cod_colab = 'E1975';
UPDATE core_personal.workers SET nome = 'JAIME MANOLO ALVAREZ TORRES', pasaporte = '123470552' WHERE cod_colab = 'E0064';
UPDATE core_personal.workers SET nome = 'JAIME NICOLAS GOYES', pasaporte = 'AY708560' WHERE cod_colab = 'E0802';
UPDATE core_personal.workers SET nome = 'JAIRO ALFONSO MUNOZ VALLE', pasaporte = 'BG734432' WHERE cod_colab = 'E1701';
UPDATE core_personal.workers SET nome = 'JAIVER JOSE POLANCO PEREZ', pasaporte = 'BA546146' WHERE cod_colab = 'E0384';
UPDATE core_personal.workers SET nome = 'JAPSIN STEVEN RUIZ PARRA', pasaporte = 'BF679443' WHERE cod_colab = 'E1513';
UPDATE core_personal.workers SET nome = 'JASIR ENRIQUE DIAZ MANJARREZ', pasaporte = 'BC329880' WHERE cod_colab = 'E1515';
UPDATE core_personal.workers SET nome = 'JAVIER DE JESUS SALAS MARTINEZ', pasaporte = 'AX751742' WHERE cod_colab = 'E1747';
UPDATE core_personal.workers SET nome = 'JAVIER FRANCISCO BALDOVINO ORTEGA', pasaporte = 'BC167879' WHERE cod_colab = 'E1435';
UPDATE core_personal.workers SET nome = 'JAVIER HUMBERTO PARRA CORREA', pasaporte = 'AY229676' WHERE cod_colab = 'E1674';
UPDATE core_personal.workers SET nome = 'JAVIER RODRIGUEZ CONTRERAS', pasaporte = 'AS213886' WHERE cod_colab = 'E1786';
UPDATE core_personal.workers SET nome = 'JAVIER SAUL PEREA CAMARGO', pasaporte = 'PA0888226' WHERE cod_colab = 'E0067';
UPDATE core_personal.workers SET nome = 'JEAN CARLO GARCIA GARCIA', pasaporte = 'BH024101' WHERE cod_colab = 'E0097';
UPDATE core_personal.workers SET nome = 'JEAN CARLO SUAREZ VALENCIA', pasaporte = 'BF929760' WHERE cod_colab = 'E2037';
UPDATE core_personal.workers SET nome = 'JEENVINSON ADALBERTO IGUARAN GRANADILLO', pasaporte = 'BC823124' WHERE cod_colab = 'E1518';
UPDATE core_personal.workers SET nome = 'JEFFERSON ANDRES OROZCO RODRIGUEZ', pasaporte = 'AX877936' WHERE cod_colab = 'E0398';
UPDATE core_personal.workers SET nome = 'JEFFERSON ANDRES VALIENTE PEREZ', pasaporte = 'AY030368' WHERE cod_colab = 'E0182';
UPDATE core_personal.workers SET nome = 'JEISON ALEXANDER GONZALEZ FARFAN', pasaporte = 'AY151855' WHERE cod_colab = 'E2110';
UPDATE core_personal.workers SET nome = 'JEISON ANDRES REYES PACHECO', pasaporte = 'AX789725' WHERE cod_colab = 'E2119';
UPDATE core_personal.workers SET nome = 'JEISON HERRERA LOZANO', pasaporte = 'BC335616' WHERE cod_colab = 'E1851';
UPDATE core_personal.workers SET nome = 'JESUS ALBERTO GONZALES FERNANDEZ', pasaporte = '123708220' WHERE cod_colab = 'E0065';
UPDATE core_personal.workers SET nome = 'JESUS ALBERTO PENARANDA VILLALOBOS', pasaporte = 'BA229290' WHERE cod_colab = 'E2121';
UPDATE core_personal.workers SET nome = 'JESUS DAVID CARDENAS RIVERA', pasaporte = 'AX913061' WHERE cod_colab = 'E0146';
UPDATE core_personal.workers SET nome = 'JESUS ELIECER ALVAREZ ORTIZ', pasaporte = 'AZ496884' WHERE cod_colab = 'E1772';
UPDATE core_personal.workers SET nome = 'JESUS HEYBER YELA MELO', pasaporte = 'BD617784' WHERE cod_colab = 'E1204';
UPDATE core_personal.workers SET nome = 'JESUS JAMES BALDEON ZUNIGA', pasaporte = '224412652' WHERE cod_colab = 'E0044';
UPDATE core_personal.workers SET nome = 'JHOBERGS JESUS PARRA DE ARCO', pasaporte = 'AZ180974' WHERE cod_colab = 'E0029';
UPDATE core_personal.workers SET nome = 'JHOJAN ESNEIDER NIÑO PARRA', pasaporte = 'BC660905' WHERE cod_colab = 'E1744';
UPDATE core_personal.workers SET nome = 'JHON ADAIMER MORALES MORALES', pasaporte = 'BC014190' WHERE cod_colab = 'E0196';
UPDATE core_personal.workers SET nome = 'JHON ALEXANDER ARENAS CASTRILLON', pasaporte = 'BG248165' WHERE cod_colab = 'E2049';
UPDATE core_personal.workers SET nome = 'JHON EDER CASTRO MONTAÑO', pasaporte = 'BG053362' WHERE cod_colab = 'E1523';
UPDATE core_personal.workers SET nome = 'JHON EINER INSUASTI TULANDE', pasaporte = 'BE016530' WHERE cod_colab = 'E1415';
UPDATE core_personal.workers SET nome = 'JHON FREDDY CABRERA AGUILAR', pasaporte = 'BE967012' WHERE cod_colab = 'E1690';
UPDATE core_personal.workers SET nome = 'JHON FREDY VELEIZANO PULIDO', pasaporte = 'AY659508' WHERE cod_colab = 'E1961';
UPDATE core_personal.workers SET nome = 'JHON JAIRO CASTAÑO POSADA', pasaporte = 'AT446373' WHERE cod_colab = 'E0040';
UPDATE core_personal.workers SET nome = 'JHON JAIRO MUÑOZ BARBOSA', pasaporte = 'AS977060' WHERE cod_colab = 'E1416';
UPDATE core_personal.workers SET nome = 'JHON JAIRO PAREJA JARAMILLO', pasaporte = 'BG029701' WHERE cod_colab = 'E1525';
UPDATE core_personal.workers SET nome = 'JHONNY ESTID QUIJANO TREJO', pasaporte = 'BE842267' WHERE cod_colab = 'E0381';
UPDATE core_personal.workers SET nome = 'JHORMAN STEVEN PINTO QUITORA', pasaporte = 'BD350783' WHERE cod_colab = 'E1852';
UPDATE core_personal.workers SET nome = 'JIM PAUL CHUNGA LUJAN', pasaporte = '124769503' WHERE cod_colab = 'E0123';
UPDATE core_personal.workers SET nome = 'JOHAN ANDRES HERRERA RUGE', pasaporte = 'BF8117775' WHERE cod_colab = 'E1670';
UPDATE core_personal.workers SET nome = 'JOHN FREDDY PEREZ RUIZ', pasaporte = 'BF595564' WHERE cod_colab = 'E0108';
UPDATE core_personal.workers SET nome = 'JOHN FREDY CASTRO JIMENEZ', pasaporte = 'AS165303' WHERE cod_colab = 'E0492';
UPDATE core_personal.workers SET nome = 'JOHN HAROLD PERENGUEZ CUARAN', pasaporte = 'BE202557' WHERE cod_colab = 'E1529';
UPDATE core_personal.workers SET nome = 'JOHNNY JAVIER BORJA MANGA', pasaporte = 'AX765156' WHERE cod_colab = 'E0268';
UPDATE core_personal.workers SET nome = 'JONATAS HERTEL LOUZADA', pasaporte = 'FY634500' WHERE cod_colab = 'E0069';
UPDATE core_personal.workers SET nome = 'JONATHAN ALEJANDRO MARTINEZ CASTIBLANCO', pasaporte = 'BD259254' WHERE cod_colab = 'E0552';
UPDATE core_personal.workers SET nome = 'JONATHAN BLANDON HINCAPIE', pasaporte = 'BC903992' WHERE cod_colab = 'E0591';
UPDATE core_personal.workers SET nome = 'JONNY ENRIQUE CURA VARGAS', pasaporte = 'BG659816' WHERE cod_colab = 'E2113';
UPDATE core_personal.workers SET nome = 'JORDY ALEXANDER ALVA PAYAC', pasaporte = '120754778' WHERE cod_colab = 'E0034';
UPDATE core_personal.workers SET nome = 'JORGE ANDRES VEGA DELGADO', pasaporte = 'AZ404504' WHERE cod_colab = 'E1698';
UPDATE core_personal.workers SET nome = 'JORGE ANTONIO RAMIREZ LUNA', pasaporte = '124949405' WHERE cod_colab = 'E1531';
UPDATE core_personal.workers SET nome = 'JORGE ARLEY ALVAREZ GONZALEZ', pasaporte = 'BD135014' WHERE cod_colab = 'E0164';
UPDATE core_personal.workers SET nome = 'JORGE EDUARDO VARGAS CASTAÑEDA', pasaporte = 'BC584849' WHERE cod_colab = 'E1532';
UPDATE core_personal.workers SET nome = 'JORGE HERNANDO AGUIRRE VELANDIA', pasaporte = 'BF223217' WHERE cod_colab = 'E1669';
UPDATE core_personal.workers SET nome = 'JORGE IVAN SARRIA ORTIZ', pasaporte = 'BH418904' WHERE cod_colab = 'E0818';
UPDATE core_personal.workers SET nome = 'JORGE LEONARDO MACHUCA GARCIA', pasaporte = 'BG215264' WHERE cod_colab = 'E1680';
UPDATE core_personal.workers SET nome = 'JORGE LUIS HUERTA OBREGON', pasaporte = '123391900' WHERE cod_colab = 'E0002';
UPDATE core_personal.workers SET nome = 'JORGE LUIS JIMENEZ BISCUMICHE', pasaporte = 'BF249367' WHERE cod_colab = 'E1534';
UPDATE core_personal.workers SET nome = 'JORGE NAYRO GARCIA OROZCO', pasaporte = 'BA511544' WHERE cod_colab = 'E0490';
UPDATE core_personal.workers SET nome = 'JORGE REINALDO GOMEZ ROJAS', pasaporte = 'BF338970' WHERE cod_colab = 'E0560';
UPDATE core_personal.workers SET nome = 'JOSE ALEXANDER CALDERON AGUDELO', pasaporte = 'BG625661' WHERE cod_colab = 'E2107';
UPDATE core_personal.workers SET nome = 'JOSE ANTONIO MORALES HURTADO', pasaporte = 'AZ752110' WHERE cod_colab = 'E0377';
UPDATE core_personal.workers SET nome = 'JOSE ANTONIO RUEDA CAMARGO', pasaporte = 'BH064654' WHERE cod_colab = 'E1875';
UPDATE core_personal.workers SET nome = 'JOSE DAYNER ACOSTA LENIS', pasaporte = 'BE657669' WHERE cod_colab = 'E0291';
UPDATE core_personal.workers SET nome = 'JOSE DE JESUS MENDOZA PADILLA', pasaporte = 'AV083614' WHERE cod_colab = 'E0163';
UPDATE core_personal.workers SET nome = 'JOSE EDUARDO NUÑEZ ESCARATE', pasaporte = '124412489' WHERE cod_colab = 'E1080';
UPDATE core_personal.workers SET nome = 'JOSE ELMES PASTES DOMINGUEZ', pasaporte = 'AY300058' WHERE cod_colab = 'E0181';
UPDATE core_personal.workers SET nome = 'JOSE FERNANDO VEGA BUITRAGO', pasaporte = 'AU365094' WHERE cod_colab = 'E0260';
UPDATE core_personal.workers SET nome = 'JOSE GUILLERMO PENA BARRERA', pasaporte = 'AT601373' WHERE cod_colab = 'E1969';
UPDATE core_personal.workers SET nome = 'JOSE HERNAN RODRIGUEZ', pasaporte = 'AAH326228' WHERE cod_colab = 'E0090';
UPDATE core_personal.workers SET nome = 'JOSE JONATHAN CANO SALAZAR', pasaporte = 'AY143348' WHERE cod_colab = 'E2101';
UPDATE core_personal.workers SET nome = 'JOSE JULIAN LEMOS ZUNIGA', pasaporte = 'BG260404' WHERE cod_colab = 'E1687';
UPDATE core_personal.workers SET nome = 'JOSE LEONARDO CALDERON MANZANO', pasaporte = 'AS409908' WHERE cod_colab = 'E1799';
UPDATE core_personal.workers SET nome = 'JOSE LISARDO LINARES', pasaporte = 'BG900657' WHERE cod_colab = 'E1825';
UPDATE core_personal.workers SET nome = 'JOSE LUIS ARENAS DIAZ', pasaporte = '223246257' WHERE cod_colab = 'E2036';
UPDATE core_personal.workers SET nome = 'JOSE LUIS CAUSADO TAMAYO', pasaporte = 'AY976250' WHERE cod_colab = 'E0399';
UPDATE core_personal.workers SET nome = 'JOSE MIGUEL ZACARIAS CHIRINOS', pasaporte = '182139448' WHERE cod_colab = 'E1795';
UPDATE core_personal.workers SET nome = 'JOSE STEVAN MURILLO MARTINEZ', pasaporte = 'BA922988' WHERE cod_colab = 'E0324';
UPDATE core_personal.workers SET nome = 'JOSE YOVANNY LOZANO GOMEZ', pasaporte = 'AU558324' WHERE cod_colab = 'E1820';
UPDATE core_personal.workers SET nome = 'JOSEPH ESTIVENS NIETO FERNANDEZ', pasaporte = 'AS287428' WHERE cod_colab = 'E1284';
UPDATE core_personal.workers SET nome = 'JOSUE ENRIQUE ZEVALLOS BENITES', pasaporte = '119253276' WHERE cod_colab = 'E0474';
UPDATE core_personal.workers SET nome = 'JUAN ALBEIRO MONSALVE MARIN', pasaporte = 'BF895966' WHERE cod_colab = 'E1843';
UPDATE core_personal.workers SET nome = 'JUAN ALBERTO RODRIGUEZ', pasaporte = 'AAH357072' WHERE cod_colab = 'E0426';
UPDATE core_personal.workers SET nome = 'JUAN BERNARDO PALACIOS RUIZ', pasaporte = '124784989' WHERE cod_colab = 'E0190';
UPDATE core_personal.workers SET nome = 'JUAN CARLOS BENAVIDES RODRIGUEZ', pasaporte = 'AW083493' WHERE cod_colab = 'E0395';
UPDATE core_personal.workers SET nome = 'JUAN CARLOS CASTRO BARRAGAN', pasaporte = 'BD209841' WHERE cod_colab = 'E2118';
UPDATE core_personal.workers SET nome = 'JUAN CARLOS CHAPARRO QUINTERO', pasaporte = 'BD815258' WHERE cod_colab = 'E0093';
UPDATE core_personal.workers SET nome = 'JUAN CARLOS NUÑEZ MORALES', pasaporte = 'AW246849' WHERE cod_colab = 'E1240';
UPDATE core_personal.workers SET nome = 'JUAN CARLOS TORRES LEON', pasaporte = '124767425' WHERE cod_colab = 'E2106';
UPDATE core_personal.workers SET nome = 'JUAN CARLOS VILLANUEVA DE LA HOZ', pasaporte = 'AX435937' WHERE cod_colab = 'E1543';
UPDATE core_personal.workers SET nome = 'JUAN CARLOS VILLANUEVA GALVIS', pasaporte = 'AS930695' WHERE cod_colab = 'E0105';
UPDATE core_personal.workers SET nome = 'JUAN DANIEL MORA PEÑALOZA', pasaporte = 'BA666566' WHERE cod_colab = 'E0263';
UPDATE core_personal.workers SET nome = 'JUAN DANIEL ROA ROSAS', pasaporte = 'BH281510' WHERE cod_colab = 'E2065';
UPDATE core_personal.workers SET nome = 'JUAN PABLO PENA ZAPATA', pasaporte = 'BG252662' WHERE cod_colab = 'E1894';
UPDATE core_personal.workers SET nome = 'JUAN PABLO PORTILLA ZAMBRANO', pasaporte = 'AS588252' WHERE cod_colab = 'E0770';
UPDATE core_personal.workers SET nome = 'JUAN QUINTANA DE AVILA', pasaporte = 'BF828969' WHERE cod_colab = 'E1726';
UPDATE core_personal.workers SET nome = 'JUAN SEBASTIAN GARCIA GARCIA', pasaporte = 'BE654702' WHERE cod_colab = 'E0102';
UPDATE core_personal.workers SET nome = 'JULIAN EDUARDO ARCO SAENZ', pasaporte = 'BD581184' WHERE cod_colab = 'E0174';
UPDATE core_personal.workers SET nome = 'JULIAN JAVIER PEARSON GUERRERO', pasaporte = 'BC124318' WHERE cod_colab = 'E2077';
UPDATE core_personal.workers SET nome = 'JULIO CESAR ANTEQUERA ALMARALES', pasaporte = 'BC071402' WHERE cod_colab = 'E0639';
UPDATE core_personal.workers SET nome = 'JULIO CESAR ELJACH BERROCAL', pasaporte = 'AS499832' WHERE cod_colab = 'E1546';
UPDATE core_personal.workers SET nome = 'JULIO CESAR MANJARRES', pasaporte = 'BG214517' WHERE cod_colab = 'E1547';
UPDATE core_personal.workers SET nome = 'JULIO CESAR VERA', pasaporte = 'AS219875' WHERE cod_colab = 'E1827';
UPDATE core_personal.workers SET nome = 'JUSED CHAMORRO MENDEZ', pasaporte = 'BF084398' WHERE cod_colab = 'E1548';
UPDATE core_personal.workers SET nome = 'KEVIN FRANKLYN LESCANO REYES', pasaporte = '122152513' WHERE cod_colab = 'E0425';
UPDATE core_personal.workers SET nome = 'KLINSMANN ANDRE COLINA MARIN', pasaporte = '199016947' WHERE cod_colab = 'E2132';
UPDATE core_personal.workers SET nome = 'LEANDRO VARGAS BETANCOURTH', pasaporte = 'BE323689' WHERE cod_colab = 'E0892';
UPDATE core_personal.workers SET nome = 'LEISER DONCEL AVILA', pasaporte = 'AY164114' WHERE cod_colab = 'E1814';
UPDATE core_personal.workers SET nome = 'LENNIN JESUS CANON CARDENAS', pasaporte = 'AX539818' WHERE cod_colab = 'E1423';
UPDATE core_personal.workers SET nome = 'LEONARDO JAVIER RIOS CORREA', pasaporte = 'BG918343' WHERE cod_colab = 'E1813';
UPDATE core_personal.workers SET nome = 'LUCAS VINICIUS FRANCO NOVAKOWSKI', pasaporte = 'GM404962' WHERE cod_colab = 'E2139';
UPDATE core_personal.workers SET nome = 'LUIGUI ARMANDO QUINES GRANADOS', pasaporte = 'L53418887' WHERE cod_colab = 'E0027';
UPDATE core_personal.workers SET nome = 'LUIS ALBERTO BUSTOS CALDERON', pasaporte = 'BD253156' WHERE cod_colab = 'E1681';
UPDATE core_personal.workers SET nome = 'LUIS ALBERTO CAMARGO NINO', pasaporte = 'BD965436' WHERE cod_colab = 'E1866';
UPDATE core_personal.workers SET nome = 'LUIS ALBERTO DIAZ CLAVIJO', pasaporte = 'AW680082' WHERE cod_colab = 'E0344';
UPDATE core_personal.workers SET nome = 'LUIS ALBERTO RAMIREZ PINEDO', pasaporte = '124194671' WHERE cod_colab = 'E0066';
UPDATE core_personal.workers SET nome = 'LUIS ALEXANDER SEPULVEDA GUERRERO', pasaporte = 'BA378154' WHERE cod_colab = 'E1942';
UPDATE core_personal.workers SET nome = 'LUIS ALFREDO APONTE ANTON', pasaporte = '120219574' WHERE cod_colab = 'E1785';
UPDATE core_personal.workers SET nome = 'LUIS ALFREDO MALAVER CARDENAS', pasaporte = 'AZ522992' WHERE cod_colab = 'E1953';
UPDATE core_personal.workers SET nome = 'LUIS ANTONIO SOTO VIDAL', pasaporte = 'BE752545' WHERE cod_colab = 'E2032';
UPDATE core_personal.workers SET nome = 'LUIS CARLOS CASTELLAR VILLARREAL', pasaporte = 'BD792126' WHERE cod_colab = 'E1873';
UPDATE core_personal.workers SET nome = 'LUIS CARLOS PEREZ GONZALEZ', pasaporte = 'BD982113' WHERE cod_colab = 'E0095';
UPDATE core_personal.workers SET nome = 'LUIS DIOMEDES RODRIGUEZ USTARIS', pasaporte = 'AW715135' WHERE cod_colab = 'E2099';
UPDATE core_personal.workers SET nome = 'LUIS EFRAIN ADRIANZEN MARCELO', pasaporte = '122272554' WHERE cod_colab = 'E1767';
UPDATE core_personal.workers SET nome = 'LUIS ENRIQUE GARRIDO CASTRO', pasaporte = '194208547' WHERE cod_colab = 'E1207';
UPDATE core_personal.workers SET nome = 'LUIS ENRIQUE LOPEZ CRESPO', pasaporte = '124286123' WHERE cod_colab = 'E2116';
UPDATE core_personal.workers SET nome = 'LUIS FELIPE TRILLOS NAVARRO', pasaporte = 'BA547454' WHERE cod_colab = 'E2112';
UPDATE core_personal.workers SET nome = 'LUIS FERNANDO BENJUMEA ORTIZ', pasaporte = 'BE724177' WHERE cod_colab = 'E1705';
UPDATE core_personal.workers SET nome = 'LUIS FERNANDO TOVAR LLAMOZA', pasaporte = 'AS553748' WHERE cod_colab = 'E0099';
UPDATE core_personal.workers SET nome = 'LUIS FERNANDO VASQUEZ ALVARADO', pasaporte = '125422139' WHERE cod_colab = 'E1846';
UPDATE core_personal.workers SET nome = 'LUIS GUILLERMO ARTEAGA AGUDELO', pasaporte = 'AZ847739' WHERE cod_colab = 'E1881';
UPDATE core_personal.workers SET nome = 'LUIS HERNANDO HINESTROZA VALENCIA', pasaporte = 'AS782526' WHERE cod_colab = 'E2014';
UPDATE core_personal.workers SET nome = 'LUIS MIGUEL VEGA FUENTES', pasaporte = 'BF200929' WHERE cod_colab = 'E0258';
UPDATE core_personal.workers SET nome = 'LUYSMER DAVID PEÑARANDA CABRERA', pasaporte = 'BA640674' WHERE cod_colab = 'E1745';
UPDATE core_personal.workers SET nome = 'MANUEL TCHIMBINJA GOMBACASSI', pasaporte = 'N2730592' WHERE cod_colab = 'E1797';
UPDATE core_personal.workers SET nome = 'MARCELO JAVIER GARCIA RUIZ DIAZ', pasaporte = 'A119903' WHERE cod_colab = 'E2117';
UPDATE core_personal.workers SET nome = 'MARCO ALEXIS VILLAMIL SUAREZ', pasaporte = 'AZ602014' WHERE cod_colab = 'E2085';
UPDATE core_personal.workers SET nome = 'MARCOS RAFAEL CASANI VALDEZ', pasaporte = 'L56279177' WHERE cod_colab = 'E1556';
UPDATE core_personal.workers SET nome = 'MARIO ALEXANDER PEÑALOZA GARCIA', pasaporte = 'AZ475234' WHERE cod_colab = 'E0505';
UPDATE core_personal.workers SET nome = 'MARIO FERNANDO ALBERCA PUICON', pasaporte = '122415866' WHERE cod_colab = 'E0467';
UPDATE core_personal.workers SET nome = 'MARIO LUIS FERNANDO PEDEMONTE RUIZ', pasaporte = '125082456' WHERE cod_colab = 'E2016';
UPDATE core_personal.workers SET nome = 'MARLO CESAR CASTILLO SILUPU', pasaporte = '123971973' WHERE cod_colab = 'E1557';
UPDATE core_personal.workers SET nome = 'MARLON BUJATO SILVERA', pasaporte = 'BF609595' WHERE cod_colab = 'E1558';
UPDATE core_personal.workers SET nome = 'MARLON SERNA URBANO', pasaporte = 'BC783911' WHERE cod_colab = 'E0366';
UPDATE core_personal.workers SET nome = 'MARTIN CAMILO SUAREZ BARRERA', pasaporte = 'AU574938' WHERE cod_colab = 'E0246';
UPDATE core_personal.workers SET nome = 'MATEO CANTILLO PAYARES', pasaporte = 'AX242434' WHERE cod_colab = 'E1727';
UPDATE core_personal.workers SET nome = 'MAURICIO TORO RAMIREZ', pasaporte = 'AW779699' WHERE cod_colab = 'E0147';
UPDATE core_personal.workers SET nome = 'MELBIN JULIO ALBOR SUAREZ', pasaporte = 'AX287058' WHERE cod_colab = 'E0003';
UPDATE core_personal.workers SET nome = 'MICHAEL ANDRES AHUMADA RUBIO', pasaporte = 'BH210996' WHERE cod_colab = 'E1994';
UPDATE core_personal.workers SET nome = 'MIGUEL ANGEL ARCAYA NORIEGA', pasaporte = '123850723' WHERE cod_colab = 'E0464';
UPDATE core_personal.workers SET nome = 'MIGUEL ANGEL CHUQUIZAPON VASQUEZ', pasaporte = '123871649' WHERE cod_colab = 'E0780';
UPDATE core_personal.workers SET nome = 'MIGUEL ANGEL GARCIA CASTRO', pasaporte = 'BF679853' WHERE cod_colab = 'E1849';
UPDATE core_personal.workers SET nome = 'MIGUEL ANGEL MARTINEZ ISAZA', pasaporte = 'AU47876' WHERE cod_colab = 'E1560';
UPDATE core_personal.workers SET nome = 'MILTHON WALTER PORRAS JIMENEZ', pasaporte = '120666395' WHERE cod_colab = 'E0792';
UPDATE core_personal.workers SET nome = 'MILTON DAVID SOSA PALLAS', pasaporte = 'D736368' WHERE cod_colab = 'E0392';
UPDATE core_personal.workers SET nome = 'MILTON JONATHAN OSORIO MARTINEZ', pasaporte = 'BF035032' WHERE cod_colab = 'E0126';
UPDATE core_personal.workers SET nome = 'MILTON OMAR MEDINA PANTA', pasaporte = '124784802' WHERE cod_colab = 'E0204';
UPDATE core_personal.workers SET nome = 'MISAEL SUAREZ SIJONA', pasaporte = 'BG942989' WHERE cod_colab = 'E2053';
UPDATE core_personal.workers SET nome = 'MOACIR DA SILVA', pasaporte = 'GD039378' WHERE cod_colab = 'E0072';
UPDATE core_personal.workers SET nome = 'NASSER MOHAMAD MERES LUNA', pasaporte = '123446084' WHERE cod_colab = 'E0423';
UPDATE core_personal.workers SET nome = 'NEIRON ENRIQUE CARCAMO REALES', pasaporte = 'BG098195' WHERE cod_colab = 'E1442';
UPDATE core_personal.workers SET nome = 'NELSON ENRIQUE MARTINEZ VEGA', pasaporte = 'BA116098' WHERE cod_colab = 'E0635';
UPDATE core_personal.workers SET nome = 'NELSON JAIME PITRE CASTILLA', pasaporte = 'BG203871' WHERE cod_colab = 'E1751';
UPDATE core_personal.workers SET nome = 'NELSON JAVIER ACOSTA SANTISTEBAN', pasaporte = 'AZ911698' WHERE cod_colab = 'E0273';
UPDATE core_personal.workers SET nome = 'NELSON ROBERTO HENAO BEDOYA', pasaporte = 'BE474832' WHERE cod_colab = 'E1714';
UPDATE core_personal.workers SET nome = 'NELSON RODRIGO MOSSOS ANDRADE', pasaporte = 'BA626823' WHERE cod_colab = 'E2009';
UPDATE core_personal.workers SET nome = 'NESTOR ALEXANDER VIERA CANALES', pasaporte = '124136527' WHERE cod_colab = 'E2007';
UPDATE core_personal.workers SET nome = 'NESTOR JAVIER BARRIOS PENA', pasaporte = 'AX368484' WHERE cod_colab = 'E2143';
UPDATE core_personal.workers SET nome = 'NICOLAS MIGUEL PEDRAZA MENDOZA', pasaporte = 'AS484348' WHERE cod_colab = 'E1563';
UPDATE core_personal.workers SET nome = 'NICOLAS RAUL MACIAS MEJIA', pasaporte = 'BA857205' WHERE cod_colab = 'E0349';
UPDATE core_personal.workers SET nome = 'NILSON MOSQUERA GOMEZ', pasaporte = 'BF347619' WHERE cod_colab = 'E0551';
UPDATE core_personal.workers SET nome = 'NIVALDO MENDES DA SILVA', pasaporte = 'GD472813' WHERE cod_colab = 'E0088';
UPDATE core_personal.workers SET nome = 'NORBEY BALLESTEROS CRUZ', pasaporte = 'AZ036428' WHERE cod_colab = 'E0447';
UPDATE core_personal.workers SET nome = 'NORBEY VARON ESQUIVEL', pasaporte = 'AW650546' WHERE cod_colab = 'E0400';
UPDATE core_personal.workers SET nome = 'NORVEY GONZALEZ LOPEZ', pasaporte = 'AT650688' WHERE cod_colab = 'E1754';
UPDATE core_personal.workers SET nome = 'ODAR JOHN REYES RAMIREZ', pasaporte = '120417894' WHERE cod_colab = 'E1076';
UPDATE core_personal.workers SET nome = 'OLMEDO ARIEL HERNANDEZ GONZALEZ', pasaporte = 'PA1279201' WHERE cod_colab = 'E2109';
UPDATE core_personal.workers SET nome = 'OMAR DAVID DIAZ MORALES', pasaporte = 'BG481892' WHERE cod_colab = 'E1753';
UPDATE core_personal.workers SET nome = 'OMAR STEVEEN SANCHEZ ROJAS', pasaporte = 'BE989548' WHERE cod_colab = 'E0367';
UPDATE core_personal.workers SET nome = 'ORLANDO JANNCARLO ACEVEDO GUZMAN', pasaporte = '124959582' WHERE cod_colab = 'E1287';
UPDATE core_personal.workers SET nome = 'ORLANDO RODRIGUEZ MADARIAGA', pasaporte = 'BA053607' WHERE cod_colab = 'E0626';
UPDATE core_personal.workers SET nome = 'OSCAR ASTORGA MUÑOZ', pasaporte = 'BC133224' WHERE cod_colab = 'E0371';
UPDATE core_personal.workers SET nome = 'OSCAR BALTAZAR GUTIERREZ PACHECO', pasaporte = '124668518' WHERE cod_colab = 'E1289';
UPDATE core_personal.workers SET nome = 'OSCAR GIOVANNI DIAZ MARTINEZ', pasaporte = 'BE470549' WHERE cod_colab = 'E1719';
UPDATE core_personal.workers SET nome = 'OSCAR JESUS MENDEZ BELLO', pasaporte = '195284959' WHERE cod_colab = 'E0465';
UPDATE core_personal.workers SET nome = 'PABLO ALBERTO RIANO BONILLA', pasaporte = 'AY830583' WHERE cod_colab = 'E1779';
UPDATE core_personal.workers SET nome = 'PABLO MANOLO ROMERO HUERTAS', pasaporte = 'BG918492' WHERE cod_colab = 'E1800';
UPDATE core_personal.workers SET nome = 'PAVEL FERNANDO GARCIA ZAPATA', pasaporte = 'BF743771' WHERE cod_colab = 'E2059';
UPDATE core_personal.workers SET nome = 'PEDRO ALEXANDER ROJAS RODRIGUEZ', pasaporte = 'AW121633' WHERE cod_colab = 'E2125';
UPDATE core_personal.workers SET nome = 'PEDRO DE JESUS DE LA HOZ SALCEDO', pasaporte = 'AZ757731' WHERE cod_colab = 'E1424';
UPDATE core_personal.workers SET nome = 'PEDRO ISIDRO CAMELO BENAVIDES', pasaporte = 'BF812041' WHERE cod_colab = 'E1573';
UPDATE core_personal.workers SET nome = 'PEDRO LUIS PADILLA VALDEZ', pasaporte = 'AY673052' WHERE cod_colab = 'E1996';
UPDATE core_personal.workers SET nome = 'PEDRO PABLO ZAVALA GALLARDO', pasaporte = '123170183' WHERE cod_colab = 'E1574';
UPDATE core_personal.workers SET nome = 'PERCY ROMEO SAAVEDRA VELASQUEZ', pasaporte = '124851508' WHERE cod_colab = 'E0200';
UPDATE core_personal.workers SET nome = 'PROSPERO SUAREZ PASTRAN', pasaporte = 'BE669200' WHERE cod_colab = 'E2060';
UPDATE core_personal.workers SET nome = 'RAFAEL ALEJANDRO HERRERA URBANO', pasaporte = 'BE913789' WHERE cod_colab = 'E1816';
UPDATE core_personal.workers SET nome = 'RAFAEL ARTURO REYES ROMERO', pasaporte = '124474638' WHERE cod_colab = 'E0327';
UPDATE core_personal.workers SET nome = 'RAFAEL CALDERON CAVIEDES', pasaporte = 'BG267967' WHERE cod_colab = 'E0634';
UPDATE core_personal.workers SET nome = 'RAFAEL ELIAS VALDERRAMA VERGARA', pasaporte = 'AX585502' WHERE cod_colab = 'E1729';
UPDATE core_personal.workers SET nome = 'RAMON EDUARDO JIMENEZ PEREZ', pasaporte = 'AT933269' WHERE cod_colab = 'E0264';
UPDATE core_personal.workers SET nome = 'RANDYS MIGUEL NIEBLES HURTADO', pasaporte = 'BG467207' WHERE cod_colab = 'E2128';
UPDATE core_personal.workers SET nome = 'RAUL AUGUSTO MIRANDA', pasaporte = 'AS469048' WHERE cod_colab = 'E1791';
UPDATE core_personal.workers SET nome = 'RAUL ERNESTO MORA MARTINEZ', pasaporte = 'AT927641' WHERE cod_colab = 'E1789';
UPDATE core_personal.workers SET nome = 'RAYMOND JOSE GARRIDO FERRER', pasaporte = 'AV590824' WHERE cod_colab = 'E0462';
UPDATE core_personal.workers SET nome = 'REINERD SALAZAR FAJARDO', pasaporte = 'BF854945' WHERE cod_colab = 'E0048';
UPDATE core_personal.workers SET nome = 'RENZO JUNIOR CHUNGA LUJAN', pasaporte = '124955101' WHERE cod_colab = 'E1426';
UPDATE core_personal.workers SET nome = 'RICARDO MILLER SANCHEZ BECERRA', pasaporte = '123153929' WHERE cod_colab = 'E0098';
UPDATE core_personal.workers SET nome = 'RICARDO RAFAEL BONILLA BLANCO', pasaporte = 'BA716922' WHERE cod_colab = 'E2091';
UPDATE core_personal.workers SET nome = 'RICHAR TAYLOR JIMENEZ CORONADO', pasaporte = 'BG744551' WHERE cod_colab = 'E2006';
UPDATE core_personal.workers SET nome = 'RICHARD ANDERSON RUIZ BARRETO', pasaporte = 'AX168756' WHERE cod_colab = 'E2146';
UPDATE core_personal.workers SET nome = 'RICHARD ANTONIO GUERRA HERRERA', pasaporte = 'BD757770' WHERE cod_colab = 'E1906';
UPDATE core_personal.workers SET nome = 'RIGOBERTO RIOS PACHECO', pasaporte = 'PA1389743' WHERE cod_colab = 'E1783';
UPDATE core_personal.workers SET nome = 'RIGOBERTO ROMERO REINA', pasaporte = 'AZ184873' WHERE cod_colab = 'E1436';
UPDATE core_personal.workers SET nome = 'ROBER HENRRY CHUMBES ROJAS', pasaporte = '124840952' WHERE cod_colab = 'E0082';
UPDATE core_personal.workers SET nome = 'ROBERTO CARLOS MARQUINA CABRERA', pasaporte = '124019978' WHERE cod_colab = 'E0510';
UPDATE core_personal.workers SET nome = 'ROBERTO CASTILLA JIMENEZ', pasaporte = 'AYO44681' WHERE cod_colab = 'E2124';
UPDATE core_personal.workers SET nome = 'ROBINSON DE FEX DIAZ', pasaporte = 'AT214523' WHERE cod_colab = 'E0299';
UPDATE core_personal.workers SET nome = 'RODNEY NEFTALI RODRIGUEZ HERRERA', pasaporte = 'PA0834185' WHERE cod_colab = 'E1678';
UPDATE core_personal.workers SET nome = 'RODRIGO ALEXANDRO AVILA DIEGO', pasaporte = '124078581' WHERE cod_colab = 'E0503';
UPDATE core_personal.workers SET nome = 'ROGER HALDER CHILCA LEON', pasaporte = '123812121' WHERE cod_colab = 'E0116';
UPDATE core_personal.workers SET nome = 'ROLANDO CATUNTA MAMANI', pasaporte = '124103780' WHERE cod_colab = 'E0036';
UPDATE core_personal.workers SET nome = 'ROLFI ESTEBAN TORRES SOTELO', pasaporte = '122085401' WHERE cod_colab = 'E0081';
UPDATE core_personal.workers SET nome = 'ROMEL YBAN TUFINIO ZOCON', pasaporte = '120663928' WHERE cod_colab = 'E0080';
UPDATE core_personal.workers SET nome = 'RONAL TAYPE HUAMAN', pasaporte = '123674732' WHERE cod_colab = 'E1072';
UPDATE core_personal.workers SET nome = 'RUBEN DARIO GUAPACHA GUARIN', pasaporte = 'AX694082' WHERE cod_colab = 'E1702';
UPDATE core_personal.workers SET nome = 'RUBEN DARIO HURTADO MURCIA', pasaporte = 'AV559510' WHERE cod_colab = 'E1579';
UPDATE core_personal.workers SET nome = 'RUBEN DARIO RINCON CORTES', pasaporte = 'BE655666' WHERE cod_colab = 'E2068';
UPDATE core_personal.workers SET nome = 'SAIR PERALTA GARCIA', pasaporte = 'BD215096' WHERE cod_colab = 'E1649';
UPDATE core_personal.workers SET nome = 'SANTIAGO AGUILAR HURTADO', pasaporte = 'BC385005' WHERE cod_colab = 'E0779';
UPDATE core_personal.workers SET nome = 'SANTOS PAULO ARCAYA NORIEGA', pasaporte = '123856495' WHERE cod_colab = 'E0310';
UPDATE core_personal.workers SET nome = 'SERGIO ALONSO ANDRADE CASTRILLON', pasaporte = 'AY747696' WHERE cod_colab = 'E0315';
UPDATE core_personal.workers SET nome = 'SERGIO ANDRES FLOREZ MARIN', pasaporte = 'BG201360' WHERE cod_colab = 'E0001';
UPDATE core_personal.workers SET nome = 'SERGIO ANDRES LANDINES BARRIOS', pasaporte = 'BA826311' WHERE cod_colab = 'E0445';
UPDATE core_personal.workers SET nome = 'SERGIO DANIEL GOMEZ ARAMBURO', pasaporte = 'BD963578' WHERE cod_colab = 'E0422';
UPDATE core_personal.workers SET nome = 'SERGIO DAVID CORDOBA TUTA', pasaporte = 'BF731010' WHERE cod_colab = 'E0446';
UPDATE core_personal.workers SET nome = 'SEVERO PABON CASTRO', pasaporte = 'BF215315' WHERE cod_colab = 'E0178';
UPDATE core_personal.workers SET nome = 'SIMION LUCIANO CHILINGANO PILLACA', pasaporte = '122006449' WHERE cod_colab = 'E0061';
UPDATE core_personal.workers SET nome = 'TIRZO GONZALEZ BOLIVAR', pasaporte = 'BE002891' WHERE cod_colab = 'E0576';
UPDATE core_personal.workers SET nome = 'ULISES HERNAN CORDOVA HERNANDEZ', pasaporte = '122375039' WHERE cod_colab = 'E0316';
UPDATE core_personal.workers SET nome = 'VICENCIO VILLAMIZAR LEON', pasaporte = 'BF770493' WHERE cod_colab = 'E1792';
UPDATE core_personal.workers SET nome = 'VICTOR ALFONSO LUQUE CONDORI', pasaporte = '122646370' WHERE cod_colab = 'E1045';
UPDATE core_personal.workers SET nome = 'VICTOR ARTURO GALVEZ PALACIOS', pasaporte = '123336473' WHERE cod_colab = 'E0475';
UPDATE core_personal.workers SET nome = 'VICTOR AUGUSTO RAMIREZ GRANDA', pasaporte = '120655791' WHERE cod_colab = 'E0368';
UPDATE core_personal.workers SET nome = 'VICTOR BLANCO BRAVO', pasaporte = 'AX786057' WHERE cod_colab = 'E0393';
UPDATE core_personal.workers SET nome = 'VICTOR DANIEL ARIAS GONZALEZ', pasaporte = 'BF015606' WHERE cod_colab = 'E1301';
UPDATE core_personal.workers SET nome = 'VICTOR EDGARDO RAMIREZ GRANDA', pasaporte = '120526074' WHERE cod_colab = 'E0343';
UPDATE core_personal.workers SET nome = 'VICTOR JAVIER RIERA FLORES', pasaporte = '173594065' WHERE cod_colab = 'E2097';
UPDATE core_personal.workers SET nome = 'VICTOR RAMON TUANAMA GARCIA', pasaporte = '124959582' WHERE cod_colab = 'E0045';
UPDATE core_personal.workers SET nome = 'WALLACE DA SILVA GOMES', pasaporte = 'FR075656' WHERE cod_colab = 'E0577';
UPDATE core_personal.workers SET nome = 'WAYNER IBARBO VERGARA', pasaporte = 'AT988426' WHERE cod_colab = 'E0092';
UPDATE core_personal.workers SET nome = 'WENDI ALBERTO GARCIA ARRIETA', pasaporte = 'AS668146' WHERE cod_colab = 'E1711';
UPDATE core_personal.workers SET nome = 'WILBER LOPEZ BALETA', pasaporte = 'AY631036' WHERE cod_colab = 'E1818';
UPDATE core_personal.workers SET nome = 'WILLIAM MORAIS DA SILVA', pasaporte = 'GH281425' WHERE cod_colab = 'E0091';
UPDATE core_personal.workers SET nome = 'WILLIAM NOE MANRIQUE MOREYRA', pasaporte = '122474825' WHERE cod_colab = 'E0075';
UPDATE core_personal.workers SET nome = 'WILLIAM NORBERTO MELO MELO', pasaporte = 'BF462864' WHERE cod_colab = 'E1939';
UPDATE core_personal.workers SET nome = 'WILLIAN VARGAS CACERES', pasaporte = '124813640' WHERE cod_colab = 'E1949';
UPDATE core_personal.workers SET nome = 'WILMAN DE AVILA MARRIAGA', pasaporte = 'AT094343' WHERE cod_colab = 'E0234';
UPDATE core_personal.workers SET nome = 'WILMAR ESTUPIÑAN ANGULO', pasaporte = 'BE288070' WHERE cod_colab = 'E0266';
UPDATE core_personal.workers SET nome = 'WILMER ANDRES AREVALO MARIN', pasaporte = 'BH135499' WHERE cod_colab = 'E1926';
UPDATE core_personal.workers SET nome = 'WILMER ANTONIO BLANCO ALVAREZ', pasaporte = 'BA973407' WHERE cod_colab = 'E2034';
UPDATE core_personal.workers SET nome = 'WILMER DE JESUS ARIZA MUÑOZ', pasaporte = 'BA779790' WHERE cod_colab = 'E0630';
UPDATE core_personal.workers SET nome = 'WILMER FERNANDO ROJAS RAMIREZ', pasaporte = 'AV774901' WHERE cod_colab = 'E1585';
UPDATE core_personal.workers SET nome = 'WILMER SEGOVIA GARCIA', pasaporte = 'AY970731' WHERE cod_colab = 'E2058';
UPDATE core_personal.workers SET nome = 'WILMER YANAYACO PINEDO', pasaporte = '124045989' WHERE cod_colab = 'E0296';
UPDATE core_personal.workers SET nome = 'WILSON ALEXANDER GOMEZ', pasaporte = 'BD498839' WHERE cod_colab = 'E2031';
UPDATE core_personal.workers SET nome = 'WILSON CHUQUIVIGUEL BRICEÑO', pasaporte = '120289518' WHERE cod_colab = 'E1586';
UPDATE core_personal.workers SET nome = 'XEMIR SOLER ROMERO', pasaporte = 'AX418409' WHERE cod_colab = 'E0111';
UPDATE core_personal.workers SET nome = 'YAMIR CUTIVA SANCHEZ', pasaporte = 'BC756010' WHERE cod_colab = 'E1371';
UPDATE core_personal.workers SET nome = 'YANNY ALBERTO HERNANDEZ LOZANO', pasaporte = 'BF389675' WHERE cod_colab = 'E1788';
UPDATE core_personal.workers SET nome = 'YEFERSON DANIEL NEIRA ESPINOSA', pasaporte = 'BH336988' WHERE cod_colab = 'E2123';
UPDATE core_personal.workers SET nome = 'YEFFERSON ZULUAGA BUITRAGO', pasaporte = 'AU926102' WHERE cod_colab = 'E0230';
UPDATE core_personal.workers SET nome = 'YEISON HUGO ANGEL CALDERON', pasaporte = 'AY358329' WHERE cod_colab = 'E2129';
UPDATE core_personal.workers SET nome = 'YESID DAVID GOMEZ ARZUAGA', pasaporte = 'BD443602' WHERE cod_colab = 'E0358';
UPDATE core_personal.workers SET nome = 'YIMI ALEXANDER TRIANA FRANCO', pasaporte = 'BG894646' WHERE cod_colab = 'E1886';
UPDATE core_personal.workers SET nome = 'YIMIS ALFREDO FERNANDEZ PENA', pasaporte = 'BD087312' WHERE cod_colab = 'E2063';
UPDATE core_personal.workers SET nome = 'YOBER HUAMAN VELASQUE', pasaporte = '123632572' WHERE cod_colab = 'E0032';
UPDATE core_personal.workers SET nome = 'YODARLI GONZALEZ BRAVO', pasaporte = 'AS426531' WHERE cod_colab = 'E0239';
UPDATE core_personal.workers SET nome = 'YOFRE DAVID ERAZO TORRES', pasaporte = 'AT882922' WHERE cod_colab = 'E0173';
UPDATE core_personal.workers SET nome = 'YONY ALEXANDER BERNAL ARCINIEGAS', pasaporte = 'AV413433' WHERE cod_colab = 'E0269';
UPDATE core_personal.workers SET nome = 'YORVY RAFAEL MARTINEZ ROMERO', pasaporte = '194343305' WHERE cod_colab = 'E2064';
UPDATE core_personal.workers SET nome = 'YUBYINER SANTIAGO CELIS', pasaporte = '119190357' WHERE cod_colab = 'E0354';
UPDATE core_personal.workers SET nome = 'YULDOR MAURICIO BOLAÑOS', pasaporte = 'AT915053' WHERE cod_colab = 'E0405';
UPDATE core_personal.workers SET nome = 'YUSSED MURADT CHAVES AMEZQUITA', pasaporte = 'BE126333' WHERE cod_colab = 'E1055';
