-- Unify MONTRA (ID: 338, Codigo: C0631) variants
-- 1. Update colaborador_por_pedido
UPDATE public.colaborador_por_pedido
SET 
  idcliente = 338,
  codcliente = 'C0631',
  cliente_nombre = 'MONTRA'
WHERE cliente_nombre IN (
  'MONTRA',
  'MONTAJE DE TRANSPORTADORES Y SISTEMAS INDUSTRIALES, S.L',
  'MONTAJE DE TRANSPORTADORES Y SISTEMAS INDUSTRIALES. S.L',
  'MONTAJE DE TRANSPORTADORES Y SISTEMAS INDUSTRIALES, S.L.'
) OR idcliente IN (338, 697);

-- 2. Update workers
UPDATE core_personal.workers
SET cliente = 'MONTRA'
WHERE cliente IN (
  'MONTAJE DE TRANSPORTADORES Y SISTEMAS INDUSTRIALES, S.L',
  'MONTAJE DE TRANSPORTADORES Y SISTEMAS INDUSTRIALES. S.L',
  'MONTAJE DE TRANSPORTADORES Y SISTEMAS INDUSTRIALES, S.L.'
);

-- 3. Update seguridade_status
UPDATE core_personal.seguridade_status
SET origem_cliente_nome = 'MONTRA'
WHERE origem_cliente_nome IN (
  'MONTAJE DE TRANSPORTADORES Y SISTEMAS INDUSTRIALES, S.L',
  'MONTAJE DE TRANSPORTADORES Y SISTEMAS INDUSTRIALES. S.L',
  'MONTAJE DE TRANSPORTADORES Y SISTEMAS INDUSTRIALES, S.L.'
);

-- 4. Update asignaciones_grupo
UPDATE public.asignaciones_grupo
SET cliente_id = 'MONTRA'
WHERE cliente_id IN (
  'MONTAJE DE TRANSPORTADORES Y SISTEMAS INDUSTRIALES, S.L',
  'MONTAJE DE TRANSPORTADORES Y SISTEMAS INDUSTRIALES. S.L',
  'MONTAJE DE TRANSPORTADORES Y SISTEMAS INDUSTRIALES, S.L.'
);
